### ISSUE TITLE
`nimbleMCMC` should have a `dimensions` argument

### ISSUE THREAD

**Issue by ashiklom** [nimble-dev/nimble#1000]
`nimbleModel` can take a named list of `dimensions` for each variable. It seems natural to pass this capability on to `nimbleMCMC`, but that's not currently possible.

**Comment by perrydv** [comment]
Thanks for the issue, @ashiklom .  The perspective taken for `nimbleMCMC` is that it is the most basic interface, and for finer-grained control a user can take advantage of the more explicit workflow of `nimbleModel`, `buildMCMC`, `compileNimble`, and `runMCMC`.  However I can see it would make sense to consider `dimensions` as basic enough that it could make sense to pass through `nimbleMCMC`.  In the past we've hesitated to expand `nimbleMCMC` because the more involved workflow is always available.

**Comment by ashiklom** [comment]
Thanks for the quick reply, @perrydv ! I agree that it makes sense to keep the simple interface simple, but `dimensions` does seem to be low-hanging fruit in terms of a (small) expansion of that interface. But, given that this seems to be a deliberate decision rather than an accidental omission, I leave it up to you. If you think the `dimensions` is worth adding, I'd be happy to submit a pull request.

**Comment by danielturek** [comment]
@ashiklom @perrydv I would support this addition, adding `dimensions` to `nimbleMCMC`.  If a PR is made please flag me to review it.  It could be made off the `devel` branch of nimble.
