### ISSUE TITLE
(Question) Convergence diagnostic and model comparison (DIC)

### ISSUE THREAD

**Issue by genwei007** [nimble-dev/nimble#102]
Hi Nimble developers,

I am just curious is there any R package of convergence diagnostic available for Nimble? I searched the manual but found nothing been mentioned. This should be a quite important step to know whether the estimates are reliable or not.

For model comparison, what kind of DIC could be used in Nimble? (same to BUGS, JAGS?) 

Thanks! :)

PK

**Comment by pistacliffcho** [comment]
Hi PK, 

While nimble does not have any specialized convergence diagnostic tools, it is designed so that a user can easily extract the results into generic R objects (via `as.matrix` on a modelValues object) which can then be inspected by any generic R package for model diagnostics. 

For example, the following code generates samples from the classic "pump" model, extracts the samples via `as.matrix` and then passes it to `coda`'s `mcmc` function. From here, you can use any of `coda`'s tools to examine your results. 


<pre><code>
library(nimble)
library(coda)

##  BUILDING THE PUMP MODEL

pumpCode <- nimbleCode({ 
  for (i in 1:N){
    theta[i] ~ dgamma(alpha,beta)
    lambda[i] <- theta[i]*t[i]
    x[i] ~ dpois(lambda[i])
  }
  alpha ~ dexp(1.0)
  beta ~ dgamma(0.1,1.0)
})

pumpConsts <- list(N = 10,
                   t = c(94.3, 15.7, 62.9, 126, 5.24,
                         31.4, 1.05, 1.05, 2.1, 10.5))

pumpData <- list(x = c(5, 1, 5, 14, 3, 19, 1, 1, 4, 22))

pumpInits <- list(alpha = 1, beta = 1,
                  theta = rep(0.1, pumpConsts$N))

pump <- nimbleModel(code = pumpCode, name = 'pump', constants = pumpConsts,
                    data = pumpData, inits = pumpInits)
c_pump <- compileNimble(pump)


## BUILDING MCMC

pump_mcmc <- buildMCMC(pump)
c_pump_mcmc <- compileNimble(pump_mcmc, project = pump)


## RUNNING MCMC AND RETREAVING SAMPLES

c_pump_mcmc$run(10000)

mcmc_samples <- as.matrix(c_pump_mcmc$mvSamples)
# as.matrix extracts the samples in a basic R-matrix
# this means it can be passed to any other function that expects
# an R-matrix, such as coda's "mcmc" function


## USING coda TO EXAMINE RESULTS

coda_samples <- mcmc(mcmc_samples)
plot(coda_samples)   
# using coda's default plotting of MCMC samples
</code></pre>

**Comment by genwei007** [comment]
Thanks so much:) How about the another previous question:
For model comparison, what kind of DIC could be used in Nimble? (same to BUGS, JAGS?) 

BTW,
1. Is it possible to do parallel chains using multiple cores, and put them into the coda_sample easily?
2. I saw the Stan manual provides another model comparison index--WAIC, is it recommended and possible to compute in Nimble?

**Comment by perrydv** [comment]
> On Dec 28, 2015, at 3:07 AM, genwei007 <notifications@github.com> wrote:
> 
> Thanks so much:) How about the another previous question:
> For model comparison, what kind of DIC could be used in Nimble? (same to BUGS, JAGS?)
> 
> BTW,
> 1. Is it possible to do parallel chains using multiple cores, and put them into the coda_sample easily?
> 
We haven’t built this directly into NIMBLE. You might be able to do it from R.
> 2. I saw the Stan manual provides another model comparison index--WAIC, is it recommended and possible to compute in Nimble?
> 
> 

We haven’t gotten around to implementing WAIC yet but it’s on our list.  Are you interested in writing it?

Perry

**Comment by paciorek** [comment]
A couple follow-up comments to Perry's response.

For parallel chains, it would be straightforward to use foreach or mclapply
or similar to run multiple chains at once. You'll need to create multiple
copies of the model - see Section 5.3.4 of the user manual - and then build
and run the MCMC for each copy of the model. Not sure about the steps of
putting them in coda_sample, but I can't imagine that would be hard, as I
think it's just an S3 class and probably not much more complicated than a
list.

WAIC should be a straightforward calculation to do via post-processing of
the model output as well, based on using NIMBLE's calculate function on the
relevant model nodes.

**Comment by perrydv** [comment]
Looks like this issue was useful and can be closed. Closing it now.
