### ISSUE TITLE
Using argument time in runMCMC instead of mcmc$run()

### ISSUE THREAD

**Issue by rpatin** [nimble-dev/nimble#1052]
Hello,
I am interested in looking at the time spent in each samplers and if it was possible to do it through runMCMC. I know it can be done through argument time in mcmc$run(time = TRUE) and I was wondering why the argument could not be passed through runMCMC (but maybe there is a good reason not to do so).
Thanks in advance et thank you all for the work on the package.
Rémi

**Comment by danielturek** [comment]
@rpatin There is no fundamentally "good" reason for this - but only that `runMCMC` is designed to be a convenience function, allowing easy use of the most common features of the MCMC.  "Lower level" fined grained control options, such as `time = TRUE`, and `reset = FALSE` are only provided via the lowest-level direct access to the MCMC, through the `mcmc$run(...)` method, which literally is calling the `run` method of the MCMC `nimbleFunction` - or more specifically, the `run` method of the specialized `nimbleFunction` created by `buildMCMC`. 

Anyway, that's a long-winded way of saying "it's that way by design, and at present there are no plans to change that".  But, rest assured, you can extremely easily do the timing via `mcmc$run`, and still get your posterior samples, etc.  Let us know if you could use help changing your code over to this lowest-level entry point to the MCMC.

**Comment by rpatin** [comment]
@danielturek Thank you for your answer. I used `runMCMC `as it was previously used in the script I got, but I will rewrite it to use `mcmc$run(...)` then. I'll let you know if I have any problem with it but it should be fine.
