### ISSUE TITLE
nimble MCMC hang

### ISSUE THREAD

**Issue by mli2830** [nimble-dev/nimble#113]
I came across a "hanging" problem when I use any nimble MCMC functions. Please see reproducible example at this repo:

https://github.com/mli2830/nimble_test

jags works perfectly via mcmcsuite but nimble hangs. I also tried starting with nimbleModel() it worked but as soon as I do any MCMC via nimble (i.e. configureMCMC, buildMCMC) it hangs.

Thanks

**Comment by perrydv** [comment]
Thanks mli2830.  I fixed the inprod bug on our devel branch.  To install from there you can do
library(devtools)
install_github("nimble-dev/nimble", ref = "devel", subdir = "packages/nimble")
(unfortunately that seems to install some packages that are suggests but not imports).

The "hang" is due to some processing involved in checking for conjugate relationships. This was written without anticipating the style of use case you've shown.  To work around it, please use "useConjugacy=FALSE" in configureMCMC.  Also note that your code should be 
modconfig <- configureMCMC(mod, useConjugacy = FALSE)
modbuild <- buildMCMC(modconfig)

or 
modbuild <- buildMCMC(mod, useConjugacy = FALSE)

(you had modbuild <- buildMCMC(mod) after modconfig <- configureMCMC(mod), so the modconfig you created wasn't actually being used)

Your model seems fine.  We should fix up the processing that gets bogged down by it.

Finally I think your model could be a good case for using a user-defined function.  If I follow, all the deterministic calculations of preker, ker, preInc, S, inc, and foi could be bundled together in one nimbleFunction (to return the vector inc[1:(lag + numobs)]), which you could then use for obsMean[j].  That would cut out the tangle of nodes and probably give you faster computation.  This is described in section 5.2.5 of the user manual and we'd be happy to help you make it work.
