### ISSUE TITLE
is the "clearNimbleFunctionsAfterCompiling" option still experimental?

### ISSUE THREAD

**Issue by zoey-rw** [nimble-dev/nimble#1130]
The user manual mentions that nimbleOptions(clearNimbleFunctionsAfterCompiling = TRUE) is an experimental way to reduce memory usage after compiling. It looks like this option has been around for a few years. Are there still reasons to avoid using this option? If it causes trouble, is it likely to be something obvious (like R crashing) or something harder to detect?

**Comment by paciorek** [comment]
No reason not to use it - any trouble that occurs should be something obvious rather than something subtle that changes computational results. It's not something that we or others use all that much, hence the lingering 'experimental' tag... Let us know if you run into any problems (in that case, feel free to re-open this issue).
