### ISSUE TITLE
`as.matrix(Cmcmc$mvSamples)` fails if nothing was monitored

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#1140]
See nimble-users message of 7/9/21.

**Comment by paciorek** [comment]
Side note: Setting nothing to be monitored seems to require either a corner case such as the user gave or  use of `resetMonitors` as using `monitors = NULL` in `configureMCMC` seems to have no effect.  I'm going to fix things so `monitors = NULL` "works", though it's not useful, presumably.

**Comment by paciorek** [comment]
I made a variety of adjustments for the no monitors case. Probably didn't catch every possible error and what is output (NULL versus empty list, etc.) may not be completely consistent across various ways to run and report MCMC, but hopefully handles most things ok.

Also, the default value for missing modelValues values is now `as.numeric(NA)` instead of `0.1`. I think this might only affect uncompiled modelValues.

As far as `monitors = NULL` that in essence is the default, which means monitor top nodes. So I will just leave as is, such that asking for `monitors = NULL` gives top nodes as well.

**Comment by paciorek** [comment]
Fixed by PR #1153.
