### ISSUE TITLE
Saving the nimble object for later analysis

### ISSUE THREAD

**Issue by GuidoAMoreira** [nimble-dev/nimble#1220]
Hello and thank you for creating such an amazing tool for MCMC (and other stuffz).

I'm still a nimble beginner and I like working with models and data which require many iterations and computing time. Therefore I usually let the computer run for a few days and after it's done, I like to save the results to some file so I can analyze them later.

This worked with Stan and others. However, with nimble I ran the MCMC with the ·$run() function and saved the object to a .rds. I later tried to recover the samples with ·$mvSamples from the object loaded with readRDS() and a null pointer is returned.

Is this a bug? Intended? Or am I just doing something wrong? I'm also surprised that the rds can take up to 500MB on disk. This means that the samples must be there, somewhere, right?

Thanks a bunch,
Guido A. Moreira

**Comment by paciorek** [comment]
Hi Guido, you need to get the samples back into an R object (rather than an R interface to what is actually a C++ object) and then save them, as one currently cannot save the C++ objects.

Here's some basic code

```
my_mcmc$run(niter)
samples <- as.matrix(my_mcmc$mvSamples)
# now save 'samples' to whatever output file format you prefer
```
We're actively working on an overhaul of the compilation system that will make it possible to save and reload the C++ objects, but it will still be a while until that is available.
