### ISSUE TITLE
Possible error with dconstraint() using transformed nodes

### ISSUE THREAD

**Issue by MHollanders** [nimble-dev/nimble#1227]
Hello,

I've been trying to put priors directly on log/logit transformed parameters to allow unbounded sampling, e.g., instead of 

y ~ dbeta(1, 1),

do

logit(y) ~ dlogis(0, 1),

which I think under the hood is equivalent to 

logit_x ~ dlogis(0, 1)
y <- expit(logit_x)

Now, I'm using dconstraint to constrain y < some value. For some chains, I get the following error message:

warning: logProb of data node constraint: logProb is -Inf. 

I also get this error when I use dconstraint to constrain logit_x. 

Curiously, I'm only getting this error on the second or third chain when I'm doing longer production runs. I have been unable to replicate this error when running ~10 chains for 100 iterations.

I realize this is a bit vague but I'd be happy to supply an example.

Matt

**Comment by paciorek** [comment]
Hi Matt,

This warning occurs when NIMBLE is initializing nodes with missing values before starting MCMC (though the warning doesn't make clear that it's happening then rather than during the actual MCMC sampling). I'm not sure how you're initializing things for your different chains, but based on the warning it seems that the initial value for `y` is violating the constraint.

Note that if you're relying on NIMBLE to do the initialization, we use the prior to initialize so the initialization doesn't account for the constraint and could well initialize at a value that violates the constraint.
