### ISSUE TITLE
Bug when simulating data from a model with a `dcar_normal` random effect

### ISSUE THREAD

**Issue by lcgodoy** [nimble-dev/nimble#1238]
Hello everyone,

I am trying to simulate data from (among others) a model with an ICAR random effect.
I followed the instructions from [this post](https://r-nimble.org/nimbleExamples/simulation_from_model.html), and it worked nicely for every model I tried to simulate except for the ones with an ICAR random effect.

Consider the piece of code (model taken from the Nimble manual) below:
```
set.seed(123)
code <- nimbleCode({
    alpha ~ dflat()
    beta ~ dnorm(0, 0.0001)
    tau ~ dgamma(0.001, 0.001)
    s[1:N] ~ dcar_normal(adj[1:L], weights[1:L], num[1:N], tau,
                         zero_mean = 1)
    for(i in 1:N) {
        log(lambda[i]) <- alpha + beta*x[i] + s[i]
        y[i] ~ dpois(lambda[i])
    }
})
L <- 8
constants <- list(N = 4, 
                          L = L,
                          num = c(3, 2, 2, 1),
                          weights = rep(1, L),
                          adj = c(2, 3, 4, 1, 3, 1, 2, 1),
                         x = c(0, 2, 2, 8))
data <- list(y = c(6, 9, 7, 12))
inits <- list(alpha = 0, beta = 0, tau = 1, s = c(0, 0, 0, 0))
Rmodel <- nimbleModel(code, constants, data, inits)
```

When I try to simulate data from the model, I get the following error:
```
nodes_sim <- Rmodel$getDependencies(c("alpha", "beta", "tau"),
                                    self = FALSE,
                                    downstream = TRUE)
Rmodel$simulate(nodes_sim)
  Error: Only one node can be accessed from a model using '[['.
```

The code works fine if I use the same logic with a CAR random effect instead. 
See below
```
set.seed(123)
code <- nimbleCode({
    alpha ~ dflat()
    beta ~ dnorm(0, 0.0001)
    tau ~ dgamma(0.001, 0.001)
    gamma ~ dunif(-1, 1)
    s[1:N] ~ dcar_proper(mu[1:N],
                         adj = adj[1:L],
                         num = num[1:N],
                         tau = tau,
                         gamma = gamma)
    for(i in 1:N) {
        mu[i] <- 0
        log(lambda[i]) <- alpha + beta * x[i] + s[i]
        y[i] ~ dpois(lambda[i])
    }
})
L <- 8
constants <- list(N = 4,
                  L = L,
                  num = c(3, 2, 2, 1),
                  weights = rep(1, L),
                  adj = c(2, 3, 4, 1, 3, 1, 2, 1),
                  x = c(0, 2, 2, 8))
data <- list(y = c(6, 9, 7, 12))
inits <- list(alpha = 0,
              beta = 0,
              tau = 1,
              gamma = 0,
              s = c(0, 0, 0, 0))
Rmodel <- nimbleModel(code, constants, data, inits)
nodes_sim <- Rmodel$getDependencies(c("alpha", "beta", "tau", "gamma"),
                                    self = FALSE,
                                    downstream = TRUE)
Rmodel$simulate(nodes_sim)
Rmodel$y
  [1]  6  9  7 12
```

Is this behavior associated with the fact that `dcar_normal` is not proper? Or is it a bug?

Thanks

**Comment by paciorek** [comment]
At a high level, the question is how we would want NIMBLE to simulate from an improper distribution. One could do this by imposing constraints and simulating in the proper lower-dimensional space. 

However, we decided simply not to simulate from the improper distribution and leave values as they are.
This works correctly for compiled code, but for uncompiled there indeed is a bug.

@lcgodoy you'll have to write your own code to simulate from the improper distribution. This would generally involve using the generalized inverse based on the eigendecomposition of the precision matrix of the improper CAR. You'd have to construct this matrix yourself. I have a[ write-up on this](https://www.stat.berkeley.edu/~paciorek/research/techVignettes/techVignette5.pdf) that may be helpful.

As far as the error in uncompiled execution, it occurs in the line of code below because `nodes` is all the nodes in `nodes_sim`.

```
currentValues <- eval(quote(model[[nodes]]), parent.frame(3))
```
I'm looking at why `nodes_sim` doesn't just contain the CAR node...

**Comment by paciorek** [comment]
Ok, I've fixed this so that uncompiled execution matches behavior of compiled. No simulation is done.

The approach in `rcar_normal` of getting values from parent frames still feels a bit fragile, but given this is in uncompiled behavior and a somewhat unusual situation, and that the result of any overlooked cases should be to error out, I'm not particularly concerned.
