### ISSUE TITLE
better error trap when constant equals 1

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1363]
This came up as a possible parallelization question, but the error seems like it is probably simply triggered by using `T` without defining it and coercion to the value 1.  Try seeing if running it serially but with `T` not set also triggers and presuming so, trap the error.

```
gapCode <- nimbleCode({
  for (t in 1:mxpq){
    psi[t] <- omega
    g[t] ~ dgamma(shape=eta, scale=psi[t]/eta)
  }
  for( t in (mxpq+1):T){
    psi[t] <- omega+inprod(durpar[1:p],g[(t-p):(t-1)])+inprod(durpar[(p+1):(p+q)],psi[(t-q):(t-1)])
    g[t] ~ dgamma(shape=eta, scale=psi[t]/eta)
  }
    for (i in 1:k){
    gamdirch[i] ~ dgamma(shape=0.5,rate=1)
  }
  for (i in 1:k){
    durpar[i] <- gamdirch[i]/sum(gamdirch[1:k])
  }
  eta ~ dgamma(shape=0.001,scale=1/0.001)
  omega ~ dgamma(shape=0.001,scale=1/0.001)
})

# Gap between refresh times:
gamma_t=as.numeric(gamma_t)

T=length(gamma_t)-20
p=2
q=2
mxpq <- max(p,q)
k=p+q+1

useWAIC <- TRUE

run_MCMC_allcode <- function(seed, data, code, useWAIC = TRUE) {
  library(nimble)
 
  T=T
  p=2
  q=2
  mxpq <- max(p,q)
  k=p+q+1
 
  # Running nimble code:
  gapModel <- nimbleModel(code = code,
                               constants = list(T = T,p=p,q=q,k=k,mxpq=mxpq,alpha = rep(0.5, k))
                               ,data = data
                               ,inits = list(eta=1,omega=0.001))
 
  mcmcConf <- configureMCMC(gapModel, monitors = c("eta","omega","durpar"),
                            enableWAIC = TRUE,useConjugacy = FALSE)
  Rmcmc<-buildMCMC(mcmcConf)
  Cmodel<-compileNimble(gapModel)
  Cmcmc <- compileNimble(Rmcmc, project = gapModel)
  samplesList <- runMCMC(Cmcmc, niter = 5000, thin=1, nburnin = 0
                         ,samplesAsCodaMCMC = TRUE, WAIC = TRUE)
  return(samplesList)
 
}

chain_output <- parLapply(cl = this_cluster, X = 1:2,
                          fun = run_MCMC_allcode,
                          data = list(g=gamma_t[1:T]), code =  gapCode,
                          useWAIC = useWAIC)

stopCluster(this_cluster)
```

**Comment by danielturek** [comment]
@paciorek I think it was the case that some historical-types of model structures, backwards indexing can just "arise" somewhat naturally, and in those cases, it should be ignored... that was what BUGS did.  So, we followed that model (of silently ignoring it), but (per usual) added an option for different behavior, if that's what a user wants (in this case, processing the backwards indexing).

Given all of that.  Perhaps one path is to introduce a warning when we ignore such indexing, but perhaps that warning itself could be suppress-able.  Or, maybe controlled by our `verbose` system option?

**Comment by perrydv** [comment]
A related issue came up recently on nimble-users [here](https://groups.google.com/u/3/g/nimble-users/c/YPyu7Xl7LC0).

(The message subject was not really relevant.)

The issue was whether if nimbleModel sees "for(i in a:b)", where `a:b` is `1:0`, does it result in no declarations? Evidently in BUGS/JAGS that is the case, and so in nested loops, e.g. "for(i in a:b[j])", one can skip some values of j for the inner loop. However we determined nimble is not supporting that. If you have your hands on these corner cases of for loop indices, is this is also relevant to decide about and handle?

My thoughts echo @danielturek 's. It does not seem like something is broken here. Given that it is a declarative language, index order should not matter. I can see some cases where it might be convenient to allow negative orders, but they seem rare. More often it seems it would be unintentional.

**Comment by paciorek** [comment]
Ok, I will add a warning when we notice backward indexing and it is being ignored (which is the default).
