### ISSUE TITLE
naming for AGHQ/AGHQuad

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#1465]
@perrydv @paul-vdb @weizhangstats  We have `buildAGHQuad` but `runAGHQ` and `summaryAGHQ`.

I'm somewhat inclined to change to `buildAGHQ`. 

I think we want to decide on a single naming convention. If we decide today or early tomorrow, we could change for the release. Or we could wait for `nimbleQuad`.

**Comment by paciorek** [comment]
I should also note "AGHQuad_" is used internally.

**Comment by perrydv** [comment]
Sorry that's partly my fault on `runAGHQ` as a late addition. I like "AGHQ" without the "uad", but I could be convinced the other way. I agree consistency will be easier in the long run.

Some names like `nQuad_` are used so that that can be an internal (member) variable name and thus leave `nQuad` available as an argument name. I don't see `AGHQuad_` but if it's there I think that kind of reason would be why.

**Comment by paciorek** [comment]
Most of our internal naming of functions/methods and objects is of the form `AGHQuad*`. I think it would be ok to leave that and have only user facing be AGHQ, namely `buildAGHQ` and `runAGHQ`.

**Comment by perrydv** [comment]
Agreed, the topic now is user-facing names.

**Comment by weizhangstats** [comment]
`buildQuad`? AGHQ is of a particular type and the more generic name `Quad` for quadrature will allow us to build in other types if of interest?

**Comment by paciorek** [comment]
I think if we added other types, we could then create a `buildQuad` as a wrapper. I'm inclined not to do that at this point.

**Comment by paul-vdb** [comment]
I think it's splitting hairs and agree with `buildQuad` big picture but `buildLaplace` and `buildAGHQ` as a wrapper in the future works just fine. I vote for `buildAGHQ` for this release. Remove the uad :)
