### ISSUE TITLE
final case of test-size?

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#157]
test-size gives behavior I'm not immediately following.  For cases when the test should fail it seems to correctly fail and count the test as a success.  But then there are a series of test failures with a message generated as "KNOWN ISSUE".  And then the last case, from line 256 of test-size.R, has a failure without that KNOWN ISSUE message.  Is that supposed to have a flag like knownProblem=TRUE or something else?

**Comment by paciorek** [comment]
There are some cases where we'd like the checking to find a problem but it
doesn't - that's when KNOWN ISSUE is reported.  There shouldn't be any
other failures, so that might be a new thing. Is this in newNodeFxns?

**Comment by perrydv** [comment]
No it’s in devel_efficiency, but I checked on devel and the same thing happens.

**Comment by paciorek** [comment]
This is a new situation caused by us disabling error reporting when a RHS calculation fails so that we don't flag the chol(NA) case as problematic. As result, model$check() no longer catches the issue in the sense of bailing out and not creating the model, but an error is reported to the user. In some sense there is not a problem with the model in this case - rather it's a problem with the dimensionality of an init, and that could of course be changed by the user.

I've changed it to a KNOWN ISSUE in test-size.R.
