### ISSUE TITLE
enhance setData for simulation studies

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#175]
We can't currently do this:
m$resetData()
m$simulate('y')
m$setData('y')

although I think that would be the natural workflow for a simulation study in which we resimulate data nodes.

The alternative is clunky
m$simulate('y')
m$setData(y = list(m$y))

**Comment by danielturek** [comment]
@paciorek just to clarify, I think they currently supported syntax is actually:

m$simulate('y')
m$setData(list(y = m$y))

But your comment is understood, none the less.

**Comment by paciorek** [comment]
Yes, I garbled it.

**Comment by perrydv** [comment]
I think 

m$simulate(‘y’, includeData = TRUE) 

is a good option for this.

I think the core of the suggestion is that m$setData should allow simple naming of variables or nodes, in which case their values should not be modified but their data flags should be set.  I like that idea (and have also run into this).  We could also consider using … to take arguments to setData so that the user need not user list().

**Comment by danielturek** [comment]
Worth talking about this option:

m$simulate(‘y’, includeData = TRUE)

Maybe I'm missing your implication here.  If y is already tagged as being data, I agree, this already works fine, and simulates new values into y.  But if y is *not* tagged as data, are you suggesting this should also have the affect of tagging y as data?  That I don't agree with.

I think a call to setData() should be necessary to do the "tagging" as data.  Which gets right back to @paciorek 's original suggestions.

**Comment by danielturek** [comment]
Nevermind, I see what you meant now.  Replacing the workflow of resetData(), simulate(), setData(), instead with simulate(..., includeData=TRUE).

**Comment by danielturek** [comment]
Perry, did you see the github PR regarding this?  Looking for something
more sophisticated?  If so, that's ok, just let me know.

Daniel

**Comment by paciorek** [comment]
Perry addressed this in full generality.
