### ISSUE TITLE
compilation error from newNodeFxns ?

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#188]
I'm not sure exactly what's going wrong here, but there's a compilation error that I'm guessing comes from the newNodeFxns changes.  This model compiles fine under v0.5-1, but not on the current devel.

this is not a minimalistic example

[data file and script can be downloaded here](https://github.com/danielturek/public/tree/gh-pages/data)

**Comment by perrydv** [comment]
getNodeFunctionIndexedInfo needed to be added to eigenizeCallsBeforeRecursing to be handled by eigenize_doNotRecurse.

A brief explanation:  In the newNodeFxns system, a line of BUGS code leads to a single instance of a class, with calculate etc. functions taking a single argument (INDEXEDNODEINFO_) that is an integer indicating which row of indexing information should be used.  Indexing information refers to indices from for-loops as well as scalar partially-evaluated values.  getNodeFunctionIndexedInfo(INDEXEDNODEINFO_, n) simply returns the value from row = INDEXEDNODEINFO_ and column = n of the table of indexing information.

The fact that there was a hitch during eignenization for a use of getNodeFunctionIndexedInfo suggests that our test suite doesn't contain much (or any) variety of vectorized expressions in BUGS code, probably because it comes from classic BUGS examples in which vectorized expressions weren't supported.

**Comment by danielturek** [comment]
Thanks for the quick fix, and the explanation @perrydv.  It works without a hitch.

FYI, running on v0.6 speeds up the MCMC by 3x for this model.  That's something to be proud of.
