### ISSUE TITLE
something wrong with newNodeFxns..... again

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#189]
Another strange inconsistancy.  Something wrong with the compiled version of a model.

A model logProb evaluates (correctly) to 221.3311 in R execution, but in the compiled execution it gives -Inf.

this example, once again, is not minimalistic.

[script and data file can be found here](https://github.com/danielturek/public/tree/gh-pages/error)

**Comment by perrydv** [comment]
I fixed this by changing the sizeProcessing scalar return type of getNodeFunctionIndexedInfo from integer to double.  It should have been double but in most uses this probably didn't matter when it was not lifted from within an expression.  But in some not uncommon uses it turned out it could be erroneously cast to integer.  This was a serious issues.  Thanks @danielturek for turning it up.

**Comment by danielturek** [comment]
Thanks again @perrydv for the quick fix.  Works great now.
