### ISSUE TITLE
Windows pragma warning

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#204]
Dao was getting this warning when using compileNimble on Windows:

model building finished.
g++ -m32 -I"C:/PROGRA~1/R/R-32~1.1/include" -DNDEBUG -I"C:/Users/dao/Documents/R/win-library/3.2/nimble/include" -I"" -DEIGEN_MPL2_ONLY=1    -I"d:/RCompile/r-compiling/local/local320/include"     -O2 -Wall  -mtune=core2 -c P_1_blocker.cpp -o P_1_blocker.o
In file included from C:/Users/dao/Documents/R/win-library/3.2/nimble/include/nimble/NimArr.h:4:0,
                 from P_1_blocker.h:3,
                 from P_1_blocker.cpp:4:
C:/Users/dao/Documents/R/win-library/3.2/nimble/include/nimble/NimArrBase.h:19:32: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]

**Comment by perrydv** [comment]
This seems to have become moot.  The pragma was to remove Windows compiler warnings about maybe-uninitialized variables, coming from getParam for vector params.  That doesn't happen anymore anyway, maybe due to NimArr<> code changes, a guess.   There was a new warning of the same kind for a generated conjugate sampler for the mcmc Wishart test.  I removed that by adding thisNodeSize <- 0 to ensure the compiler sees it is initialized.
