### ISSUE TITLE
two copies of Eigen in installed package

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#205]
n v0.6 one can end up with both Eigen and Eigen_local  in the installed package.
In 0.5-1 configure.ac there was a line with 'mv' on Eigen_local
when using the Eigen provided with Nimble (or a 'rm' when using a
system Eigen), both of which make sense, but now there is a 'cp'
of Eigen_local when using Nimble's copy of Eigen and the 'rm' is
commented out.

Perhaps this is an issue with
building binaries on Mac (maybe Windows too?) using:
R CMD INSTALL -l location --build nimble
if one omits the -l then things happen within the source directory.

**Comment by perrydv** [comment]
I think I see what is going on here.  When installing from source directories (not tarball), we want cp because that preserves Eigen_local, but then we end up with both in the installed directory.  When installing from tarball, we want mv to avoid having both in the installed directory.  I have a solution where the configure can detect if it is in a tarball and use mv instead of cp.  But then we're still left with the problem when installing from source directories.  

Backing up a step, can you remind me why we have Eigen_local instead of simply Eigen in the first place?  I remember it solved a problem but I don't remember what.

One solution might be that we use Eigen instead of Eigen_local during development and then make creation of Eigen_local a step in our release recipe and ensure the configure script will then mv Eigen_local to Eigen.

**Comment by paciorek** [comment]
1) I'm not following what you mean by installing from source directories. I
guess it relates to the ongoing issue of using R CMD INSTALL on Windows or
Mac and having it modify the local directory for you. When I install on
Linux, I do R CMD build to create a tarball and then R CMD INSTALL on that
tarball. In neither of those steps is the local directory affected with the
obvious exception that the tarball is placed into nimble/packages.
Similarly when I do R CMD build and then R CMD INSTALL on the resulting
tarball on my Mac, I don't have any local files affected.

I'm wondering if local files are only affected when using R CMD INSTALL
--build and if the 'solution' is when anyone does that on Mac/Win for them
to use the -l flag so that the activities are done in a separate directory.
If so, we could go back to doing 'mv' instead of 'cp'.

2) Here's an email thread from Sept 2015 with my understanding of
Eigen_local vs Eigen:

=============from Chris ===========================================
Hi Duncan,

I'm starting to walk through the errors/warnings when checking the Nimble
package use R CMD check --as-cran.

I'm sure I'll have more questions for you, but here is a first, hopefully
quick one.

R CMD check complains about having Eigen_local in the top-level in the
nimble directory.

So I'm moving it to inst/Eigen_local and then having autoconf commands move
from there to inst/include/Eigen.

But having done that it occurs to me to ask if there is a reason to not
just put the Eigen_local stuff in inst/include/Eigen from the get-go.

=================also from Chris ========================

hmm, I guess we don't want it in inst/include/Eigen to start with in case
we end up using Eigen already on the system...

So I'll just have Eigen_local be in inst and either move or remove it
depending on whether we are using our provided Eigen or using what is on
the user's system.

Let me know if you see any issues.

**Comment by perrydv** [comment]
R CMD INSTALL nimble
does work in the nimble directory structure and then copies it to the install location

R CMD INSTALL nimble_0.6.tar.gz (which would be preceded by R CMD BUILD) unpacks the tarball in a temporary directory, does work there and copies it to the install location.  This can lead to subtly different outcomes than above.

I think -l makes it do the work in a different location.

Yes we could solve the issues by requiring only specific incantations of R CMD BUILD and INSTALL, but it would be nice if things just worked however one wants to use those tools.

Question: Instead of having Eigen_local and either copying it (usually) or removing it (if a user has their own Eigen), could we instead have Eigen and either do nothing (usually) or not include it in the installation (if a user has their own Eigen).  Was there any other reason for Eigen_local?

**Comment by paciorek** [comment]
ah... I never do "R CMD INSTALL nimble" so didn't realize that was an
option...

Answer: seems reasonable - we can change configure.ac to do a 'rm' of
include/Eigen if user has own Eigen. Seems like that would address the
issue. Would be helpful to have Duncan weigh in in case we're not
considering something.

**Comment by paciorek** [comment]
hmm, that said if we trigger a 'rm' then someone using R CMD build nimble
may end up causing inst/include/Eigen to get removed from the repository if
not careful...

**Comment by perrydv** [comment]
I think it will be a little more complicated than that, but not much.  Oh, I see the comment you just added -- yes, exactly.   It would be safe to rm it when installing from a tarball since those are not in a github repo any more.   If someone installs from their github repo directories and wants their own copy of Eigen used, we could just rename include/Eigen to  include/Eigen_not_used.  Then, in that case only, there would be one extraneous copy of Eigen, but there would never be two copies installed.

Does the CRAN building process always work from a tar.gz or zip (Windows)?

Also this change would be a big change in the repo, because we'd remove Eigen_local and add Eigen.

**Comment by paciorek** [comment]
CRAN always starts with the .tar.gz that we upload to them.

I'm not sure how the configuration step would know how it was being invoked
so not sure how we could conditionally invoke a 'rm'.

If we can't do that, then presumably we do as follows:  we put Eigen in
inst/include/Eigen only and then

a) if local Eigen is used we move inst/include/Eigen to
/inst/include/Eigen_not_used
b) if local Eigen not used we simply leave things as is

If so, either of us can make that change to configure.ac and do the move of
the Eigen directory in the repo. Since I think my use of Git from the
command line tends to be safer than your usage of the Git GUI, I'll propose
that I make these two changes.

One danger here is that if one of us uses a local Eigen and is doing R CMD
BUILD nimble, then we could accidentally end up with Eigen_not_used in the
repository but that will only occur if we mess up our Git usage and is
easily reversible in any event.

chris

**Comment by perrydv** [comment]
On branch installation-issues I've moved inst/Eigen_local to inst/include/Eigen permanently.  When a user supplies a copy of Eigen, if installation is being done from a tarball, Eigen will be deleted by configure prior to the copying done by R's standard installation steps.
