### ISSUE TITLE
genLocalMakeVars and global variable AutoconfInfo

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#207]
in makevars.R, there is a function genLocalMakevars that appears never
to be used. (Same thing with sameDir in that same file.

genLocalMakevars makes use of AutoconfInfo, which is a global variable
that is not defined anywhere. And so R CMD check complains.

**Comment by perrydv** [comment]
genLocalMakevars can be called from createMakevars, but I think it's correct that the conditionals to do so would never be TRUE under the new installation variants, so it will never be called.  I believe AutoconfInfo was an old system for relaying information from the configure script to R by way of configure-generated code in config.R, but it appears now fully defunct.  I like keeping around a genLocalMakevars function since it's short and we have it.  But I've replaced EIGEN_INC (which took its value from the old AutoconfInfo) to take "".  The upshot is that if genLocalMakevars is ever needed again and the user has their own Eigen installation to point to, we will need to get the location of their Eigen installation passed in and set as the EIGEN_INC value.  But for now let's assume that need will not arise.
