### ISSUE TITLE
libnimble.a "has no symbols" on Mac

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#208]
Building on mac results in this message:

R CMD INSTALL -l /tmp/foo --configure-args="--enable-lib=false"  --build nimble
then it says:
"Making nimble libnimble.a"
but also
"/opt/local/bin/ranlib: file: libnimble.a(NFxnUtils.o) has no symbols"
"/opt/local/bin/ranlib: file: libnimble.a(Values.o) has no symbols"

**Comment by perrydv** [comment]
It's not that libnimble.a has no symbols.  It's that two of the .o files being linked together into libnimble.a have no symbols.  That's because the files had content at some point but no longer do but are still on a list of what should be included in creating libnimble.a.  I have that fixed locally for now while working on more installation issues but will close this because it is a simple issue.
