### ISSUE TITLE
Using nimbleFunctionList without nimbleFunctionVirtual?

### ISSUE THREAD

**Issue by NLMichaud** [nimble-dev/nimble#220]
I'm wondering if it is possible to create a `nimbleFunctionList` populated with `nimbleFunction`s without using a `nimbleFunctionVirtual`.  For example, the following code makes a list of `littleFunction`s which do not inherit methods from a `nimbleFunctionVirtual`.  All of the functions in the list are the same `nimbleFunction`, but with different setup values. 

Running the code gives the error message:
 `Error: An element being put in a nimbleFunctionList is not valid. It may not have the right contains (base class)`
 I am curious if there is some other way of creating a `nimbleFunctionList` without using `nimbleFunctionVirtual`.

```
bigFunction <- nimbleFunction(
  setup = function(N) {
    functions <- nimbleFunctionList(littleFunction)
    for(n in 1:N)
      functions[[n]] <-littleFunction(n)
  },
  run = function() {
    returnType(integer(0))
    sum_N <- 0
    for(n in 1:N) 
     sum_N <- sum_N + functions[[n]]$run()

    return(sum_N)
  }
)

littleFunction <- nimbleFunction(
  setup = function(n){},
  run = function(){
    returnType(integer(0))
    return(n)
  }
)

testFunction <- bigFunction(5)
```

**Comment by scastano** [comment]
Good question, I'm curious too!

From my short experience with Nimble, I understand that nimbleListFunction can apply just to nimbleFunctionVirtual objects and cannot be defined within 'run' code, given that so far nimble functions (nfs) don't deal with lists.
You can always define one by one, specializations of several nfs in the setup of your main function, or several specializations of a given nf, which could be the case of your example: 

`baseClass <- nimbleFunctionVirtual(
    run = function() {returnType(integer())}
)

littleFunction <- nimbleFunction(
    contains = baseClass,
    setup = function(n){},
    run = function(){
        returnType(integer())
        return(n)
    }
)

bigFunction <- nimbleFunction(
    setup = function(N) {
        functions <- nimbleFunctionList(baseClass)
        for(n in 1:N)
            functions[[n]] <- littleFunction(n)
    },
    run = function() {
        returnType(integer(0))
        sum_N <- 0
        for(n in 1:N)
            sum_N <- sum_N + functions[[n]]$run()
        return(sum_N)
    }
)

mybigFunction <- bigFunction(10)
mybigFunction$run()
cmybigFunction <- compileNimble(mybigFunction)
cmybigFunction$run()`
 
Unless you have a good reason, you could move the variable 'n' from 'setup' to 'run' in littleFunction, so after minor changes in baseClass and bigFunction, get the latter working too.


Maybe you had in mind a more complex case, but at least for your simple example, you can avoid using a list :

`## I moved the n variable to run code, instead of 'setup', so I specialize just once in bigFunction
littleFunction <- nimbleFunction(
    setup = function(){},
    run = function(n = integer()){
        returnType(integer())
        return(n)
    }
)

## It works if the output of mylittleFunction is an integer
bigFunction <- nimbleFunction(
    setup = function() {
        mylittleFunction <- littleFunction()
            },
    run = function(N = integer()) {
        sum_N <- 0
        for(n in 1:N)
            sum_N <- sum_N + mylittleFunction$run(n)
        return(sum_N)
        returnType(integer())
    }
)

BF <- bigFunction()
BF$run(10)
cBF <- compileNimble(BF)
cBF$run(10)`



I'm sure developers have a more detailed answer to your question, so let's wait !!

**Comment by danielturek** [comment]
Yes @scastano is right that this (trivial) example can be changed to have `n` be a runtime argument to `littleFunction`.  But I suspect @NLMichaud has a deeper need for the setup function specialization.

Assuming that to be true, the modified code provided by @scastano is the correct, and the only, way to make this work (currently) in NIMBLE.  The argument to `nimbleFunctionList()` must be the result of calling `nimbleFunctionVirtual()`, in this case the `baseClass` object, then all (specialized) nimbleFunctions used to populate that `nimbleFunctionList` object must "contain" `baseClass`.

My version, essentially identical, is below, with changes marked as comments:

```
bigFunction <- nimbleFunction(
      setup = function(N) {
          functions <- nimbleFunctionList(littleFunction_virtual)  ## CHANGE
          for(n in 1:N)
              functions[[n]] <-littleFunction(n)
      },
      run = function() {
          returnType(integer(0))
          sum_N <- 0
          for(n in 1:N) 
              sum_N <- sum_N + functions[[n]]$run()
          return(sum_N)
      }
  )

## NEW
littleFunction_virtual <- nimbleFunctionVirtual(
    run = function() {
        returnType(integer(0))
    }
)

littleFunction <- nimbleFunction(
    contains = littleFunction_virtual,  ## NEW
    setup = function(n){},
    run = function(){
        returnType(integer(0))
        return(n)
    }
)

testFunction <- bigFunction(5)
testFunction$run()
CtestFunction <- compileNimble(testFunction)
CtestFunction$run()
```

Please reopen this issue if there is any lingering question.

**Comment by perrydv** [comment]
I'm re-opening this to provide a developer to-do to make it work without the virtual layer if it should not be needed.
