### ISSUE TITLE
environment name in cpp filename?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#222]
Is this new that we have "R_GlobalEnv" in names of .cpp/.o/.so files? Don't imagine anything is wrong, but just noticed this for the first time. Previously "nimble" was in the place of "R_GlobalEnv".  Just wanted to flag in on the off-chance sometime was up.

g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o P_2_nfRefClass_R_GlobalEnv8008_27_08_19_37.so P_2_nfRefClass_R_GlobalEnv80.o -L/tmp/nimrange/nimble/CppCode -lnimble -Wl,-rpath=/tmp/nimrange/nimble/CppCode -llapack -lblas -L/usr/lib/R/lib -lR

**Comment by perrydv** [comment]
Is this from a nimbleFunction defined in an R session (as opposed to package source code)?  Shouldn't be new but let me know if you find otherwise.

Here is the processing flow leading to the name:

nimbleFunction takes a `name` argument, which if absent is created by a call to `nf_refClassLabelMaker(envName = environmentName(where))`.  Then `className` is set to `name`.  The `nf_refClassLabelMaker` is a function created at the top of nimbleFunction_core by `labelFunctionCreator('nfRefClass')` (defined in all_utils.R).  That nfRefClass string becomes a permanent component of any nimbleFunction name, and the `envName` argument is pasted into it.  That `environmentName(where)` returns the name of the where environment, which will return R_GlobalEnv for a user-defined nimbleFunction for which `where = .GlobalEnv`.  So that's how R_GlobalEnv gets pasted into the nimbleFunction className.  That `className` becomes `generatorName` in `nimbleProjectClass::compilerNimbleFunction`, which then becomes part of the `filename` of the `cppProjectClass`.  When `cppProjectClass::compileFile` is called, that `filename` is passed as the `name` argument, which is pasted into the `outputSOfile` name.
