### ISSUE TITLE
Running the Rmcmc first causes compilation of Rmcmc to crash

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#246]
If the Rmcmc algorithm is executed before calling compileNimble(Rmcmc), then compilation of the Rmcmc algorithm will fail.

Reproducible example:

```
library(nimble)

code <- nimbleCode({   a ~ dnorm(0, 1)   })
Rmodel <- nimbleModel(code, inits = list(a=0))
Rmcmc <- buildMCMC(Rmodel)

Rmcmc$run(10)    ## IF THIS LINE IS EXECUTED

Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)  ## THEN THIS LINE FAILS (see below)

compiling... this may take a minute. Use nimbleOptions(showCompilerOutput = TRUE) to see C++ compiler details.

Warning, mismatched dimensions in assignment: samplerTimes <<- initialize(0, 1, size(samplerFunctions)). Going to browser(). Press Q to exitFALSE
Called from: sizeAssignAfterRecursing(code, symTab, typeEnv)

Browse[1]> 
debug: if (assignmentTypeWarn(LHS$type, RHStype)) {
    message(paste0("Warning, RHS numeric type is losing information in assignment to LHS.", 
        nimDeparse(code)))
}
Browse[2]> 
```

**Comment by paciorek** [comment]
This also occurs in 0.6-1 so not a result of recent changes...

**Comment by perrydv** [comment]
Well I see what is happening.  In buildMCMC, samplerTimes is established as a vector in setup code.  But in this case there is only one sampler.  So if the Rmcmc is run, then in the run code, samplerTimes ends up with length of 1.  And if the compilation happens after that, inspection of samplerTimes leads to the conclusion it should be a scalar.  And that causes compilation of samplerTimes <- numeric(length(samplerFunctions)) to fail because it thinks the assignment is "scalar <- vector"

Thinking about a solution.  Ideas welcome.

AFAIK this is not related to recent changes.

**Comment by perrydv** [comment]
I could see workarounds for buildMCMC so users don't encounter the problem in this particular case.  But this is a glitch that could happen in other situations too.

**Comment by perrydv** [comment]
Here are a couple of more general options:

1. We could arrange to record some type information (dimensionality and double/integer/logical) of any numeric/integer/logical objects included in setupOutputs immediately after setup code is run.  This could be preserved even if uncompiled execution modifies the objects.  Then makeTypeObject (which inspects types of setupOutputs) can refer to that saved information.

2. We could allow a more explicit setup type declaration system, so a programmer can directly state that samplerTimes (e.g.) will be a vector double.  Obviously the c(0,0) trick is a bit kludgy.

These are not mutually exclusive options.

**Comment by danielturek** [comment]
Understood.  Yes, I can also imagine work-arounds to put into buildMCMC to
prevent this, but still could happen in other situations.

I didn't mean to open a whole can of worms here.  But as Perry pointed out,
it does get at the existing awkwardness in trying to define vector
quantities in setup code.  A more refined system for this might be in
order, but I didn't realize this problem would suggest such a (potentially)
large change.

**Comment by perrydv** [comment]
Agreed: this is a can of worms.  It relates to some other future directions I've been thinking of to be more flexible with numeric types.

So for now I suggest the smallest workaround as follows:

In run():
samplerTimes <<- numeric(length(x) + 1) ## add the +1 so it's always a vector

In getTimes():
return(samplerTimes[1:(length(samplerTimes)-1)])

Then we can discuss the more general situation instead of rushing to a quick fix for 0.6-2.

**Comment by danielturek** [comment]
Sounds good.  The suggested changes were made, and pushed to devel.

It appears to work fine, pending a larger system-wide upgrade to address this.  Closing issue.

**Comment by danielturek** [comment]
Sounds good.  The suggested changes were made, and pushed to devel.

It appears to work fine, pending a larger system-wide upgrade to address
this.  Closing issue.
