### ISSUE TITLE
warning is issued from using values(...) <- X assignment

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#25]
nimbleFunction() issues a warning (from reference class creation) whenever we use the assignment form of values() <-

This can be seen by creating such a NF:

nfdef <- nimbleFunction(
    setup = function(model, nodes) {},
    run = function(p = double(1)) {
        values(model, nodes) <- p
    }
)

**Comment by danielturek** [comment]
Warning message: Warning message:
In .checkFieldsInMethod(def, fieldNames, allMethods) :
  local assignment to field name will not change the field:
    values(model, nodes) <- p
 Did you mean to use "<<-"? ( in method "run" for class "nfRefClass61")

**Comment by perrydv** [comment]
This happens because we generate R reference class definitions for nimbleFunctions.  Objects created in setup code are class fields, so R expects assignment by <<-.  It is awkward.  We could code-process to switch <- to <<-, but we'd have to be sure we could isolate all cases correctly.  We've hesitated to add more layers of code processing that has to occur at the time of nimbleFunction definition, but we could.  Maybe it is only values(model, nodes) and model[[node]]?  Alternatively is there a way to turn off this warning from R?

**Comment by perrydv** [comment]
moved to wiki
