### ISSUE TITLE
Something off with model$values() <<- ...

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#254]
Can't use the syntax model$values(nodes) <<- newValues.

However, values(model, nodes) <<- newValues works fine.

reproducible example:

library(nimble)
code <- nimbleCode({
    for(i in 1:5) {
        a[i] ~ dnorm(0, 1)
    }
})
constants <- list()
data <- list()
inits <- list(a = rep(0,5))
Rmodel <- nimbleModel(code, constants, data, inits)

nfDef <- nimbleFunction(
    setup = function(model) {
        newValues <- rep(1, 5)
        nodes <- 'a'
    },
    run = function() {
        ##values(model, nodes) <<- newValues    ## this one works fine
        model$values(nodes) <<- newValues    ## this causes failure
    }
)

##Error in makeAssgnFcn(e[[1]]) :

**Comment by perrydv** [comment]
I think we did not implement assignment in the manner you tried because the syntax

object$method(arg) <- value

is not allowed in R's class systems.  

Did you see anywhere in our documentation stating it is supported?  After searching the user manual I think that we could improve documentation of model$values() for getting values (is it mentioned anywhere?) and make clear it does not work for assignment.

**Comment by danielturek** [comment]
No, it's not mentioned anywhere.  I just assumed that both assignment and access using model$values() worked.  Good to know.  Perhaps worth clarifying this in the manual.

**Comment by perrydv** [comment]
From subsequent discussion we've decided not to support model$values().
