### ISSUE TITLE
should getVarNames have includeData argument?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#271]
A variable can be a mix of data and non-data, so not clear to me this should be an option.

**Comment by danielturek** [comment]
Legitimate question.  To add to the questions,

(1) I found no instances in the entire package of calling getVarNames() which use the includeData argument.

(2) It looks like it should error out anytime includeData=FALSE, the opposite of the default value.  It uses an object `tm`, which is not defined anywhere I can find:
`allData <- unlist(lapply(mget(ans, envir = tm$isDataEnv, inherits = FALSE, ifnotfound = TRUE), all))`

Upon testing, it does error out, if you ever provide includeData=FALSE.

Being that the implementation doesn't work, and it's never used anywhere, I'm tempted to comment it out in the code base;  or change it so that a developer's warning is issued, if that case is ever invoked.

Other thoughts, @paciorek or @perrydv ?

**Comment by danielturek** [comment]
Additionally, this `includeData` argument, and the error-prone implementation, were added to the getVarNames() method by @perrydv , in commit b5acc90df29926cd8261a79371dc61e0cdf63a45, in April 2015, with commit message "fixing getVarNames and default handling of nimCopy", in case that helps jog memory.

**Comment by perrydv** [comment]
I don't recall the history of this option, but I agree it is evidently defunct.  Let's try removing it.  As long as we are not code-generating and constructing the string "includeData" by pasting ;-), your search on all uses in the code base, which I verified, seems sound.  I agree about tm being an obvious symptom of being defunct.

On principle it doesn't seem like a bad option to provide, with the intention that if any node in a variable is data then that variable would be omitted if includeData = FALSE.  But since we don't use it let's try removing it.

**Comment by danielturek** [comment]
I actually more agree with Chris's hesitations about this, that any sort of includeData argument doesn't make sense, with our notion of "variable".  Maybe this can become another great NIMBLE debate.

**Comment by perrydv** [comment]
Well at least we're agreed to remove it for now.

**Comment by danielturek** [comment]
Done.  Commented it out, with an explanatory comment.

Nice catch @paciorek.  Closing issue.
