### ISSUE TITLE
Do we want R's recycling rule behavior for nimNumeric, nimMatrix, nimArray? 

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#280]
On devel I have (previously) made it possible for the values argument to nimNumeric, nimMatrix, or nimArray to be non-scalar.  This provides a new way to cast between dimensionalities, e.g to initialize values of nimNumeric from a matrix object.  Question: If the values argument is shorter than the object being created, do we want to fill extra space with zeros or repeat the values argument (use R's recycling rule).  Doing the latter is arguably consistent with the behavior when values is a scalar and hence intended to fill the entire new object.  But the behavior in different cases is not completely consistent so I want to determine what what we want and then make it all consistent.

Example:
```
v <- nimNumeric(c(1, 2), length = 4)
## should v be [1, 2, 0, 0] or [1, 2, 1, 2]
```

**Comment by danielturek** [comment]
I'll just say I'm glad you're being cautious with adding "recycling", since it would be hard to really mimic what R does with this, and I think it would be bad to mislead users that we really provide R-like recycling, when in fact only a very small set of cases is handled.

My initial reaction is to only allow (1) scalar "values" which fill the entire structure, or (2) "values" containing the exactly required number of elements (even if a different dimension), so no recycling is necessary.  But I certainly could be swayed, depending on how easy it is to add general recycling.

**Comment by danielturek** [comment]
Oh, also, I don't like the "pad with additional 0's, as necessary" solution, since that's not R-like at all.

**Comment by perrydv** [comment]
Recycling rule is feasible to implement.  It is fully implemented on devel for distribution functions.  The framework used to do so comes to a point with a single macro line in C++ .  This could make it feasible to automatically convert many kinds of nimbleFunctions to recycling rule behavior.  That is not the crux of the implementation issue on the topic of this issue, but anyway it is feasible.

As drafted, a warning message is emitted if the values is non-scalar and doesn't match its target.  Bailing out at run-time would actually be more of a pain than just emitting such a message.

**Comment by paciorek** [comment]
I'm also cautious about having full recycling but agree that scalar
recycling is very useful, and current setup of having a warning seems
reasonable.

One other case that is not full recycling but could be quite handy is using
recycling with a matrix or array to replicate rows/columns, so that is
obviously an in-between case despite my caution above...

**Comment by perrydv** [comment]
we did implement recycling rule with user control over behavior
