### ISSUE TITLE
Running a compiled function crashes RStudio

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#296]
To reproduce: http://rpubs.com/fritzo/compiler_demo

**Comment by danielturek** [comment]
I think this is an easy one.  Specifying arg1 and arg2 as double(2) in the
run function definition means *2-dimensional* arguments, which is what the
compiled version is expecting. (i.e. arrays or matrices).

So either change the argument specifications to "arg1 = double(1)", to a
vector such as c(0.0, 0.5), or change the values of arg1, arg2, and
expectedResult to be R matrices (or dimension=2 arrays).  (for example,
array(0, c(2,2)).

**Comment by perrydv** [comment]
Right, this error *was* caught, but in the manner of our current run-time error-trapping, we emit an informational message and continue execution.  A topic that came up in our discussion earlier this week is that our run-time error trapping (from both permanent and generated C++) has been stable for a while, so it could make sense to make them bail out of execution and return safely to R.

I am going to close this issue since it is not a bug but leads to a more general feature request.  Let's make a wiki page or project to keep track of ideas for that.

**Comment by fritzo** [comment]
The current warn-and-continue behavior of assertions leads to a bad user experience, in my case crashing RStudio and causing me to lose about 30 minutes of unsaved work. I'll write up a little NIM_ASSERT(-,-) macro in C++ to avoid this pain in the future.

**Comment by perrydv** [comment]
That would be great.  See [section 6.2 of Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Error-handling) for R's API to stop() and warning().  I'd guess error() is a good way to bail out back to R.  You could start by using it at the warning you triggered, which is in inst/include/nimble/RcppNimbleUtils.h for testing purposes.  Then we can build it into generated run-time checks ("assertions" in the exprClass objects).  I note that in the particular case you triggered, we could probably provide correct treatment for wrong number number of dimensions or wrong scalar type, but at the time we preferred not to.

**Comment by fritzo** [comment]
Fixed by #297
