### ISSUE TITLE
Move tests from inst/tests/ to tests/testthat/

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#300]
We should just get it over with after this release. @fritzo is happy to volunteer.

**Comment by paciorek** [comment]
Great, thanks. But please check the "writing R extensions" manual to make
sure this is consistent with what CRAN wants.

**Comment by perrydv** [comment]
I'm not sure this is the right way to go.  I think we didn't do it previously because there are steps when R will automatically run anything in the tests directory.  E.g. step 19 of R CMD check (section 1.3.1 of [writing R extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html), which I think means that when CRAN checks a submitted package it will run what is in tests.  It is less clear from the documentation but may be the case that tests are also run upon installation (section 1.1.5).  In any case, our idea from past discussion was that our complete test suite is too heavy (hours) to include for CRAN checking, so we've kept with the "deprecated" but very useful inst/tests location.  We could consider adding *small* tests for R CMD check that could help ensure things are set up correctly without grinding through every MCMC test, DSL test, etc.

**Comment by paciorek** [comment]
Moving to nimbleCoreTeam.
