### ISSUE TITLE
unhelpful error when providing wrong dimension input argument

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#301]
This can be seen in this example with {d,r}mnorm_chol, but I suspect the issue is more general.
Also, at the moment, if the problem occurs in a block of code, the setSizes error doesn't flag which line the error occurs on, so it is hard to debug. At the least, let's catch the lack of a $nDim element and point to the specific line where the issue is. This is failing in sizeRmultivarFirstArg().
```
tmp=nimbleFunction(run=function(x=double(2)) {
out = rmnorm_chol(1,0, x, prec_param=0)
 returnType(double(1))
 return(out)
 })
> compileNimble(tmp)
compiling... this may take a minute. Use 'showCompilerOutput = TRUE' to see C++ compiler details.
Error in code$args[[returnSizeArgID]]$nDim : 
  $ operator is invalid for atomic vectors
Error: There is some problem at the setSizes processing step for this code:
 {
    out = rmnorm_chol(n = 1, mean = 0, cholesky = x, prec_param = 0)
    return(out)
}
```

**Comment by perrydv** [comment]
This was a fairly particular situation.  A multivariate `rDIST` function is among the cases where during compilation the target of assignment is moved into the first argument of a C++ call.  The [size processor where this is handled](https://github.com/nimble-dev/nimble/blob/07a4206c26e674e2f3bb97cf53ed9c41461409fc/packages/nimble/R/genCpp_sizeProcessing.R#L2809) uses a list of information indexed by the rDIST name.  One piece of information is which argument should be used to provide the size of the return value.  For `rmnorm_chol`, this is the `mean` argument.  And it broke because the mean was provided as a scalar, which was not anticipated because it must be a vector.  So I put in a specific check for this case. [PR](https://github.com/nimble-dev/nimble/pull/305)

I did not check `dmnorm_chol`.  It may error out but should do so via a different pathway.

The opening comment of this issue raises the larger question of specific error trapping.  Note we have two layers operating here.  When a size processing checks for a specific error, it can generally provide the statement and expression where it happened, using `stop(exprClassProcessingErrorMsg(code, [detailed message]), call. = FALSE)`.  [Example](https://github.com/nimble-dev/nimble/blob/07a4206c26e674e2f3bb97cf53ed9c41461409fc/packages/nimble/R/genCpp_sizeProcessing.R#L2827).

Both specifically trapped errors and non-specifically trapped errors are caught by the `try()` wrapper to the call to [`exprClasses_setSizes`](https://github.com/nimble-dev/nimble/blob/07a4206c26e674e2f3bb97cf53ed9c41461409fc/packages/nimble/R/RCfunction_compile.R#L212),  In that case, all that is known is there was an error somewhere in a potentially large block of code, which is indeed not that helpful.  At the time, it an improvement on incomprehensible R errors.

It occurs to me that we could have the master recursion function, [`exprClasses_setSizes`](https://github.com/nimble-dev/nimble/blob/07a4206c26e674e2f3bb97cf53ed9c41461409fc/packages/nimble/R/genCpp_sizeProcessing.R#L103) stick information about what statement or expression is currently being handled into the `typeEnv` (which has become a general place to store information needed to persist through size processing).  Then if the general `try()` catches an error, it could look in the `typeEnv` to see where the processing was when it stopped.  This may not be foolproof during some of the more complicated code transformations (if an error occurs partway through modifying the AST), but it could be informative most of the time.

**Comment by paciorek** [comment]
Ok, now the message is as follows. I think there's more we want to do longer-term in terms of error messages to make more clear what the issue is, but this points the user to the right place to look now.

```
Error : Expected 0 to be an expression.
 This occurred for: nimArr_rmnorm_chol(mean=0,cholesky=ARG1_x_,prec_param=0)
 This was part of the call:  out = nimArr_rmnorm_chol(mean=0,cholesky=ARG1_x_,prec_param=0)
Error: There is some problem at the setSizes processing step for this code:
 {
    out = rmnorm_chol(n = 1, mean = 0, cholesky = x, prec_param = 0)
    return(out)
}
```
