### ISSUE TITLE
issue with casting of integer in run code

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#303]
There seems to be an issue with using an integer with nimMatrix(). Haven't investigated at all, apart from noting:

1) `m = as.double(length(targetAsScalar))` eliminates the error
2) omitting the 'matrix()' and just producing a vector in the run code has no error

```
code = nimbleCode({
 mu[1:3] ~ dmnorm(z[1:3], prec = Q[1:3,1:3])
})

m = nimbleModel(code)
cm = compileNimble(m)

mynf = nimbleFunction(
setup = function(model, node) {
      targetAsScalar = model$expandNodeNames(node, returnScalarComponents=TRUE)
      m = length(targetAsScalar)
},
run = function() {
 out = matrix(1/sqrt(model[[node]])[2:m], nrow = m-1, ncol = 4)
returnType(double(2))
return(out)
})

rnf = mynf(m, 'mu[1:3]')
cnf = compileNimble(rnf, project = m, showCompilerOutput = TRUE)

P_3_nfRefClass_R_GlobalEnv88.cpp:20:128: error: member reference base type 'int'
      is not a structure or union
  ...0, (m - 2) + 1, 1)).array(), 1, 1, (m).cast<double>() - 1, 4);
                                        ~~~^~~~~
P_3_nfRefClass_R_GlobalEnv88.cpp:20:140: error: expected '(' for function-style
      cast or type construction
  ...0, (m - 2) + 1, 1)).array(), 1, 1, (m).cast<double>() - 1, 4);
                                                 ~~~~~~^
P_3_nfRefClass_R_GlobalEnv88.cpp:20:142: error: expected expression
  ...0, (m - 2) + 1, 1)).array(), 1, 1, (m).cast<double>() - 1, 4);
                                                         ^
```

**Comment by perrydv** [comment]
This was a bug in the new eigen casting system.  Prior to 0.6-4, if we had A + B, with both non-scalar, but `A` integer and `B` double, compilation would fail because C++ eigen operators always expect matching types.  Now there is a new step used by many eigenization handlers that inserts eigen's casting (e.g., `A.cast<double>()), allowing `A+B` to be converted to eigen C++ correctly.  It was not anticipated that scalars would ever get into this step.  However it happens in a case like `A + B + c` where `c` is a scalar.  The whole expression is eigenized due to `A` and `B` being non-scalar.  Then the casting operation would be done to `c`.  In the reproducible example above, `m-1` was annotated as scalar double because `m` is integer and `1` double (debatable, but safe).   Since eigenization is done only for an entire statement (not just an expression within a statement), the need to eigenize the first argument triggered eigenization of `m-1`, which should have been harmless but with the new casting system led to the buggy eigen-casting of scalar `m`.  I added a check so eigen casting will never be done to a scalar.   [PR](https://github.com/nimble-dev/nimble/pull/305)
