### ISSUE TITLE
norm in R and C differ

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#40]
norm() in R and C nimble functions differ as the R default seems to be the "1" norm (the 'type' argument) and the C version is the Frobenius

**Comment by perrydv** [comment]
I think we knew that and that is why norm is not in Table 5.4 of the manual since we consider it not working in a consistent way.  But apparently it is still in the compiler's list of valid Eigen operations and so  compiles successfully.  For the moment, do you want to try taking it out of the operator lists in genCpp_operatorLists.R and see if that successfully generates a compilation error instead of working in an inconsistent way?

**Comment by paciorek** [comment]
Two thoughts.
1) if we think this might be useful to users, perhaps just have it error
out on the R side?
2) convert on the R side to mimic the C behavior, perhaps by converting to
nimNorm? I'm happy to do this if this is what we want.

**Comment by perrydv** [comment]
> On May 5, 2015, at 10:26 PM, Christopher Paciorek <notifications@github.com> wrote:
> 
> Two thoughts.
> 1) if we think this might be useful to users, perhaps just have it error
> out on the R side?
> 2) convert on the R side to mimic the C behavior, perhaps by converting to
> nimNorm? I'm happy to do this if this is what we want.
Maybe we should stick to providing behavior consistent with what R does, so flip this.  And then if we want what Eigen does, we can provide a different keyword for that.  What do you think?

>

**Comment by paciorek** [comment]
I took this out of the operators list. Reasoning being that since we now allow user-provided functions in BUGS code, it would be straightforward for a user to write whatever norm function they want.
