### ISSUE TITLE
provide acceptance rate history for RW samplers?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#436]
In preparing a M-H example for the JSM workshop, I realized we don't store the acceptance rate history. This would be useful for pedagogical purposes as well as for user diagnosis of sampler behavior.

@danielturek, @perrydv what do you think about adding a 1-d array into the RW and RW_block samplers that keeps the acceptance rate from each adaptation period for adaptive samplers, while for non-adaptive we simply store the number accepted over the entire sampling period?

Other ideas welcome.

On a related note, nimbleOptions(buildInterfacesForCompiledNestedNimbleFunctions = TRUE) is pretty clunky for a purpose like this. We might revisit how we handle this.

**Comment by perrydv** [comment]
IIRC we used to store the acceptance rate history and then we stopped doing so because it seemed excessive and unnecessary except for pedagogical or diagnostic purposes.  If we put it back in, I would vote for having it be controlled by an option.  

I don't follow your comment on the nimbleOption, but I think you are referring to how one could get access to the acceptance rate if it is stored, or other member data for that matter.  When that option is off, the way to do it is with `valueInCompiledNimbleFunction( <compiled nimble function>, <name of data>, <optional value if setting instead of getting)`.

**Comment by paciorek** [comment]
my comment about the nimbleOption was just that I'm envisioning explaining to my workshop audience that they have to invoke this obscure option in order to see information about the behavior of the sampler.

As I muse on it more, maybe I should just calculate the acceptance manually based on the unthinned chain. 

But let's discuss briefly at our next regular meeting.

**Comment by danielturek** [comment]
If it's helpful:

both the RW sampler and RW_block sampler have (permantently in there)
commented out code, the lines which end with ## scaleHistory.  You can't
miss what I'm talking about if you look for it, or just search for
"scaleHistory"

If you comment in these lines in the RW sampler, it will record the scale
history (proposal sd), and provide useful access functions (member methods)
for extracting it, either on the scale of the samples (for plotting against
sample traceplots), or on a reduced scale, that of the adaptation intervals.

Commenting this code in for the RW_block sampler does the same, but both
for the scale history, and also proposal covariance history, again with
access functions (member methods) for returning it on the scale of
adaptation intervals, or that of the samples.

**Comment by paciorek** [comment]
Will be addressed by PR #665.
