### ISSUE TITLE
already-split vertices are not stripped out of set of elements 

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#444]
Here's an example of where "w[1:2]" is a vertex, so in step 11d of genExpandedNodeAndParentNames3(), we have a place in origElementID_2_vertexID for w[1:2]. It is never stripped out, so elementNames ends up with an empty character string for the first "element". 

```
code = nimbleCode({
    w[1:2] <- rep(1,2) 
    z <- w[1]
})
m = nimbleModel(code)
```

Should we strip out from elementID_2_vertexID and elementNames any such "element" without a name?

**Comment by perrydv** [comment]
It is not clear to me that this is a problem, or if it is relied on anywhere.  Note that `origElementID_2_vertexID` is used only during processing that leads to the `maps`, but the final version is `elementID_2_vertexID`.  It appears that the elementIDs are initialized from the vertexIDs, and then additional elementIDs are added as needed to ensure a complete set exists.  The vertexIDs contain, in the example given, one for `w[1:2]`, one for `w[1]` and one for `w[2]`.   These have types (`maps$types`) "determ", "LHSinferred" and "LHSinferred", respectively.  This is all as it should be.  Due to initializing elementIDs from vertexIDs, we end up with an elementID for `w[1:2]` (named "") that isn't really needed. That bit of residue seems pretty minor.  Inspection of elements of `maps$vars2ID_elements` suggests it will never be used.  We could try removing it if that would help your current work.

**Comment by paciorek** [comment]
it wasn't a problem for me -- just noticed it in the process of looking carefully at the maps for  some dynamic index cases, so I'm fine with leaving as is, just wanted to mention in case it caused you any concerns.

**Comment by paciorek** [comment]
Closing this so issues list is not littered with items we don't have plans to address.
