### ISSUE TITLE
Add unit tests; remove some end-to-end tests

### ISSUE THREAD

**Issue by fritzo** [nimble-dev/nimble#474]
NIMBLE tests are painfully slow. This impedes development and discourages developers from writing more tests. One way to speed up tests is to separate tests of the compiler from tests of algorithms, so that algorithms need not run the entire compiler chain end-to-end.

**Components with no unit tests:**

- `MCMC_samplers`: These are tested in end-to-end tests via `test_mcmc()` in `test_utils.R`.

**Comment by paciorek** [comment]
I'd say let's have this be a Wiki item / discussion at the planning meeting
rather than a Github issue.

Also, to me the impediment to test-writing is the effort involved in
writing them. The time to run them doesn't bother me that much. I do my
development work and then the tests are a check I haven't messed things up
-- I guess I'm using them in a less real-time way than Fritz is.

**Comment by fritzo** [comment]
The way I usually use unit tests is to keep tests under 5minutes (ideally around 1minute), and make lots of tiny commits each of which passes tests. I feel highly productive using this workflow, and I feel I could have higher productivity developing on nimble if the tests ran quicker.

But I'll close this and move discussion to the wiki.
