### ISSUE TITLE
Error with logical runtime arguments of nested NFs

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#54]
I would love for code like this to work.  Something goes wrong with the logical runtime arguments for *nested* nimble functions.

The R function works fine.
The compilation gives a nice error message.

nfDef1 <- nimbleFunction(
    setup = function() {},
    run = function(a = logical()) {
        if(a) print('a is TRUE')
        if(!a) print('a is FALSE')
    }
)

nfDef2 <- nimbleFunction(
    setup = function() {
        myNF <- nfDef1()
    },
    run = function() {
        myNF$run(TRUE)
        myNF$run(FALSE)
    }
)
        
nf <- nfDef2()
nf$run()
## a is FALSE
Cnf <- compileNimble(nf)

**Comment by danielturek** [comment]
That's funny, Markdown interpreted my "double hash symbols" as Header2 tags, and made my R comments into big, bold headings!  That was not my intent.  Check this issue on Github website if you don't see it in the email.

Daniel

**Comment by perrydv** [comment]
The issue is that we don't currently convert R logical arguments in the compiler.  Handling of logicals in C++ got set aside because C++ is weird with vector<logical> and we didn't deal with it at the time.  Note that you can get by using integers or operators that will behave correctly in C++.  So either:

myNF$run(1)
myNF$run(0)

or

myNF$run(1 > 0)
myNF$run(1 < 0)

or

a <- 1 > 0
myNF$run(a)

will work.

**Comment by perrydv** [comment]
I fixed this.  The issue was a little different than I thought.  We weren't keeping R logicals through the generation of exprClass objects.  Now they are kept and converted to numeric.
