### ISSUE TITLE
new error with the "no member named 'block'" compilation error

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#595]
This seems to relate to #530.

In branch efficient_dcat_ddirch_conjugacy, I'm trying to add an altParam to dcat that is 'ncat = nimDim(prob)[1]', which I can then use to improve the efficiency of the conjugate dcat-ddirch sampler (that sampler only needs the length of 'prob' but currently it actually gets all the values of 'prob' and  then finds the length).  In trying to do this I added nimDim to nimbleOrRFunctionNames and to UnaryOperators so that compilation could go through.  However, compilation of the model is failing.

Here's the example that errors:
```
   n <- 100
    alpha <- c(10, 30, 15, 60, 1)
    K <- length(alpha)
    p <- c(.12, .24, .09, .54, .01)
    y <- rmulti(1, n, p)
    y <- rep(seq_along(y), times = y)
    
    code <- nimbleCode( {
        for(i in 1:n)
          y[i] ~ dcat(p[1:K])
        p[1:K] ~ ddirch(alpha[1:K])
        for(i in 1:K) {
            alpha[i] ~ dgamma(.001, .001);
        }
    })
    
    inits <- list(p = rep(1/K, K), alpha = rep(K, K))
    data <- list( y = y)
    constants = list(K=K, n=n)
    m = nimbleModel(code,inits=inits,data=data,constants=constants)
    cm = compileNimble(m)
```
Error msg is:
```
P_1_code_nfCode.cpp: In member function ‘virtual double y_L2_UID_4::getParam_0D_double(int, const indexedNodeInfo&) const’:
P_1_code_nfCode.cpp:68:30: error: ‘class NimArr<1, double>’ has no member named ‘block’
 PARAMANSWER_ = ((**model_p)).block(nimSeqByD(1,5,1,0)).dim()[0];
                              ^
```
with the error occurring in the getParam function that is being created because of the additional altParam.

**Comment by perrydv** [comment]
The problem is that `dim(prob)[1]` used in a nodeFunction method is automatically expanded to `dim(prob[1:5])[1]`, which triggers the bug.  You can see the expanded version in `m$nodeFunctions$y_L2_UID_4$getParam_0D_double`.  I can fix handling of `dim`, but, in the meantime, the simpler `length(prob)` should compile (for use in the model, you'll need to add it to `nimbleOrRFunctionNames`)  and would seem to be what you need.  Will that work?

Note 1: The C++ generated by `length(prob[1:3])` is correct but unfortunately inefficient, triggering a copy of `p[1:3]` before determining its length.

Note 2: A solution for allowing an operator in model code should not need to include adding to an operator list like `unaryOperators`.  It should already be on necessary such lists.

**Comment by perrydv** [comment]
To put that another way, performance won't be much different than if you write `length(m$getParam('prob'))` into your custom sampler code, if that makes sense to do.

**Comment by paciorek** [comment]
If dim is fixed, would it also invoke a copy? That copy of a possibly long 'prob' vector is precisely what I am trying to avoid.

 As a side note, the sampler in question is conjugate and if I explicitly do anything with 'prob' in the conjugacy calculations, the conjugacy system end up allocating space for and making a copy of 'prob'.

**Comment by paciorek** [comment]
I ended up using length() as suggested. This was actually addressed last fall.
