### ISSUE TITLE
segfault when trying to modify in place.

### ISSUE THREAD

**Issue by vandenman** [nimble-dev/nimble#654]
Hi, I was making a model and noticed a segfault whenever I try to do:

```
# this crashes
for (d in 1:2) {
  aMatrix[1:4, d] <- aMatrix[1:4, d] * aVector[d]
}
```
Making an explicit copy (like below) avoids the crash.
```
for (d in 1:2) {
  aMatrixCopy[1:4, d] <- aMatrix[1:4, d] * aVector[d]
}
```

Attached a reproducible example. I'm using the latest CRAN version (0.6-8) on windows 10.

[nimbleError.zip](https://github.com/nimble-dev/nimble/files/1635191/nimbleError.zip)

**Comment by NLMichaud** [comment]
Thanks for the error report @vandenman.  The reason this model doesn't build correctly is that each line of BUGS code that is provided to a call to `nimbleModel` defines a node in that model.  Since BUGS is a declarative language, each node can be defined only once in model code.  Thus, when you attempt to redefine  `aMatrix[1:4, d]` as ` aMatrix[1:4, d] <- aMatrix[1:4, d] * aVector[d]`, you're providing NIMBLE with two definitions for many of the same nodes, such as `aMatrix[1, 1]`, which is not allowed.  Creating a second matrix node in your model to store the result of the multiplication (as you do in your second example) is one way to get around redefining the `aMatrix` nodes.  Additionally, a node in NIMBLE cannot be both stochastic (i.e. following a probability distribution using the `~` symbol), and deterministic (a fixed calculation given the other model parameters, denoted by the `<-` symbol). 

It seems like the recursive definition of `aMatrix` given in ` aMatrix[1:4, d] <- aMatrix[1:4, d] * aVector[d]` exposed a particularly ugly error in model building that, as you noted, causes R to crash without a warning or error message.  We'll work to provide a more informative message in the future, thanks again for the notice!
