### ISSUE TITLE
improve efficiency of model$check

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#67]
1) top-level check that calculate(model) returns valid number
2) (possibly) if top-level check fails, try calculate on each variable and check that all values for variable are valid; exclude 'valid' variables from the for loop over nodes that are checked individually

**Comment by danielturek** [comment]
model$check() has been modified to include a top-level check: if calculate(model) returns a valid logProb value, then model-checking is considered complete.  Otherwise, detailed checking of individual nodes is carried out.

Efficiency could be improved further by checking model variables one at a time, to assess of calculate() returns a valid number, and the variable values themselves are valid.  However, this approach opens the door to two problems, and hence has not been implemented:
(1) the presence of RHS only nodes in a variable, which don't have calculate() methods,
(2) non-sequential node declarations, e.g. x[1] <- ... , x[3] <- ...., will necessarily leave a value of NA contained in the variable x, which will fail this test.

The issue of model$check() efficiency can be revisited if we determine it's problematically slow.  Otherwise, this will remain an open option for enhancement.

**Comment by danielturek** [comment]
@paciorek talked @danielturek into improving efficiency of model$check().  Now only does a full node-wise check of variables when necessary.
