### ISSUE TITLE
fix nimble dpotrf_ issue with new igraph package

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#71]
NIMBLE is unable to locate dpotrf_ LAPACK routine when igraph version 1.x.x is loaded.

Note, this is a different igraph issue than was fixed previously.

**Comment by paciorek** [comment]
I'm going to play around with this a bit this morning hopefully.

The 0.7.x igraph did not have any Lapack code included but the 1.x.x does,
in the src/CHOLMOD folder, and this is presumably causing some conflict.
dpotrf is declared there in src/CHOLMOD but not defined.

**Comment by paciorek** [comment]
This is either fixed or worked-around. I will open another issue with Duncan to make sure what I did is what we want, but I think this gets things workign again so we can build and install against igraph 1.x.x.

A few notes:
We have not been linking lapack directly into libnimble.so or nimble.so. But libnimble.so uses dpotrf.
I believe that we were actually pulling dpotrf somehow via igraph because igraph.so links to lapack.so

Somehow, even though igraph 1.x.x links to lapack.so this was no longer working and so dpotrf was not being found when loading libnimble.so.  This may somehow relate to the fact that new in igraph 1.x.x there is a src/CHOLMOD directory that has some stuff related to Lapack, including related to dpotrf. dpotrf is declared in several places in that directory as are some synonyms for dpotrf (LAPACK_dpotrf, igraphdpotrf, etc.).

Following a note that I saw in /usr/share/R/include/R_ext/Lapack.h, I added $(LAPACK_LIBS) nad $(BLAS_LIBS) to PKG_LIBS in src/Makevars.in.  The result is that we link in lapack and blas explicitly now when creating nimble.so when building and installing nimble. (open question is whether lapack and blas should be being linked into libnimble.so instead). I left out the $(FLIBS) that R_ext/Lapack.h mentions because that seems to want to pull in libgfortran and that may not be available on some systems (e.g. Macs). Despite leaving out FLIBS, things seem fine  I have not thought carefully about this though.
