### ISSUE TITLE
possible scoping issue with R execution of nimbleFunction with resized matrices

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#724]
This came up in Claudia's work. Here's a simplified example. Perhaps I am doing something wrong?

Compiled execution is fine, but uncompiled it doesn't seem to realize that 'samples' is now 5x5 and so can't assign into the newly allocated space (unless one does `samples[2,2] <- 3`.

Haven't delved into this; just reporting it.

```
mynf <- nimbleFunction(
    setup = function(){
        samples <- matrix(0, nrow=1, ncol=1)
    },
    run = function() {
        setSize(samples, 5, 5)
        samples[2,2] <<- 3  
        returnType(double(2))
        return(samples)
    })
rnf = mynf()
rnf$run()
#Error in `[<-`(`*tmp*`, 2, 2, value = 3) : subscript out of bounds
cnf=compileNimble(rnf)
cnf$run()  # runs fine
```

**Comment by perrydv** [comment]
The problem is that `setSize` in R assigns an object to `samples`, but it does not check whether `samples` is local or a class member.  In this case it ends up creating a local `samples` which is 5x5, but then the next line assigns to the non-local `samples`, which is a  different object. It's somewhat surprising this hasn't come up before.

I'll submit a PR to fix this, but I note that `samples <- matrix(nrow = 5, ncol = 5)` seems better and works.  It also allows control over initialization and type.

**Comment by paciorek** [comment]
Claudia needs to modify the size at run-time. Is your comment about `samples <- matrix(nrow = 5, ncol = 5)` suggesting she do something differently than creating a 1x1 matrix in setup and then doing a setSize in the run code?

**Comment by danielturek** [comment]
In case Perry is travelling (I believe he is), I think the suggestion is to create the `samples` matrix in the `setup` function just then same, then in the `run` function, rather than using `setSize` to resize the matrix, as currently written, and is not functioning correctly, instead use `samples <- matrix(...)` in the `run` function, which will correctly resize the already-existing `samples` matrix.

**Comment by paciorek** [comment]
ah, thanks!

**Comment by perrydv** [comment]
Yes, that is what I meant.  But also this PR does fix the behavior of `setSize`.
