### ISSUE TITLE
Untrapped errors, when deterministic LHS transformation accidentally uses "~"

### ISSUE THREAD

**Issue by danielturek** [nimble-dev/nimble#812]
The title says it all. There are (apparently) two different untrapped errors, when a user writes a BUGS model, with a LHS transformation, accidentally using ~ when it's actually a deterministic delclaration, and should be using <-.

Examples of both below.

```
library(nimble)

## EXAMPLE 1

code <- nimbleCode({
    logit(x) ~ a
})
constants <- list()
data <- list()
inits <- list(a = 0)
Rmodel <- nimbleModel(code, constants, data, inits)
## defining model...
## Error in code[[3]][[1]] : object of type 'symbol' is not subsettable

## EXAMPLE 2
## even more obscure...

code <- nimbleCode({
    logit(x) ~ a + b
})
constants <- list()
data <- list()
inits <- list(a = 0, b = 0)
Rmodel <- nimbleModel(code, constants, data, inits)
## defining model...
## Registering the following user-provided distributions: + .
## Error in FUN(X[[i]], ...) : 
##   checkDistributionFunctions: density function for + is not available.  It must be a nimbleFunction (with no setup code).
```

**Comment by paciorek** [comment]
Actually, this occurs without the LHS transformation:

```
code <- nimbleCode({
    x ~ a
})
constants <- list()
data <- list()
inits <- list(a = 0)
Rmodel <- nimbleModel(code, constants, data, inits)
# Error in code[[3]][[1]] : object of type 'symbol' is not subsettable
```

Time-permitting, I will deal with this for 0.11.0.

**Comment by paciorek** [comment]
I have mostly fixed this in branch `issue_812` by adding checks at the beginning of `replaceDistributionAliases`.

However, giving a more informative error for `x ~ a + 7` is trickier because I am checking if the RHS is a call. `a+7` is the call `+(a,7)` and I'm not sure of a way to distinguish it from a call to a named function. So the error that `+` is not a distribution is logically consistent with R's treatment of operators, but still probably confusing to a user.

I'm simply checking against a manual list of operators to detect that situation.

**Comment by paciorek** [comment]
Ok, done. The checking for operators needed to be done in `checkDistributionFunctions`.
