### ISSUE TITLE
Change the way first contribution is handled in conjugate samplers to avoid Windows compiler warning

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#91]
At the moment the conjugate samplers are written so they compile to the following C++

firstTime = 1; 
for(i=1; i<= static_cast<int>(dependents_dpois_nodeFunctions.size()); ++i) {
 if(firstTime == 1) {
  firstTime = 0;
  contribution_shape = dependents_dpois_values[(i) - 1];
  contribution_rate = dependents_dpois_coeff[(i) - 1];
 } else {
  contribution_shape = contribution_shape + dependents_dpois_values[(i) - 1];
  contribution_rate = contribution_rate + dependents_dpois_coeff[(i) - 1];
 }
}

This generates Windows compiler warnings that contribution_[shape | rate] may be uninitialized in the last 2 lines (since it can't follow the logic here).

Can we change it (around lines 592-623 of MCMC_conjugacy), maybe to something like this:
if(dependents_dpois_nodeFunctions.size() > 0) {
    contribution_shape = dependents_dpois_values[0]; // of course [1] in R
    contribution_rate = dependents_dpois_coeff[0];
  if(dependents_dpois_nodeFunctions.size() > 1) {
    for(i=2; i<= static_cast<int>(dependents_dpois_nodeFunctions.size()); ++i) {
     contribution_shape = contribution_shape + dependents_dpois_values[(i) - 1]; // of course [i] in R
    contribution_rate = contribution_rate + dependents_dpois_coeff[(i) - 1]; 
   } 
   }
}

We could also add an 'addTo' DSL function that would generate to += in C++.

**Comment by danielturek** [comment]
I don't believe the solution proposed above would work, since the key point of this is that the "contribution" terms be initialized to 0 (or a zero-vector, or 0-array), then cumulatively sum the contributions from **any different dependent distributions which are present ** -- and in full generality, we don't know which dependent distributions have a non-zero number of terms, so we don't know when each "contribution" term will first be used.

I worked around this in a different manner.  I added logic to the conjugacy system to infer the dimensionality of each "contribution" term, then it initializes each such term to either 0, a 0-vector, or a 0-array, as appropriate.  Then code surrounding the dependent distributions is simplified, since it need only do a += operation (or the equivalent, since we don't support +=   ).  Future conjugacy cases could arise where this inference won't work, but it will stop and print a helpful error message.

Ran the conjugacy testing section of test-mcmc.R, and it appears to work.

Closing this issue, since the warnings hopefully should stop in Windows now.
