### ISSUE TITLE
Reproducibility of chains

### ISSUE THREAD

**Issue by ys-xue** [nimble-dev/nimble#919]
I am trying to get results from exactly reproducible chains so that the journal we are submitting to is able to check our code. The example in NimbleUserManual 8.0 does not give exactly the same chain even after I use `set.seed()` or add the option `setSeed = TRUE/ some number`. Below please find the code I was running, using nimble 8.0. Thanks!

```r
library(nimble)

pumpCode <- nimbleCode({ for (i in 1:N){
  theta[i] ~ dgamma(alpha,beta)
  lambda[i] <- theta[i]*t[i]
  x[i] ~ dpois(lambda[i])
}
  alpha ~ dexp(1.0)
  beta ~ dgamma(0.1,1.0) })
pumpConsts <- list(N = 10,
                   t = c(94.3, 15.7, 62.9, 126, 5.24,
                         31.4, 1.05, 1.05, 2.1, 10.5))

pumpData <- list(x = c(5, 1, 5, 14, 3, 19, 1, 1, 4, 22))

pumpInits <- list(alpha = 1, beta = 1,
                  theta = rep(0.1, pumpConsts$N))

pump <- nimbleModel(code = pumpCode, name = "pump",
                    constants = pumpConsts, data = pumpData, inits = pumpInits)


pumpConf <- configureMCMC(pump, print = TRUE)
pumpConf$addMonitors(c("beta"))

Cpump <- compileNimble(pump)

pumpMCMC <- buildMCMC(pumpConf)
CpumpMCMC <- compileNimble(pumpMCMC, project = pump)

set.seed(1)
samples1 <- runMCMC(CpumpMCMC, niter = 100, setSeed = 1)
head(samples1)
# alpha      beta
# [1,] 0.3735462 1.8396427
# [2,] 0.3735462 0.3678855
# [3,] 0.3735462 0.4084392
# [4,] 0.3735462 0.4528228
# [5,] 0.3735462 0.5411883
# [6,] 0.3735462 0.3161430

set.seed(1)
samples2 <- runMCMC(CpumpMCMC, niter = 100, setSeed = 1)
head(samples2)
# alpha      beta
# [1,] 0.5206529 0.5656616
# [2,] 0.4757193 0.6802904
# [3,] 0.4757193 0.5768246
# [4,] 0.4757193 0.6054277
# [5,] 0.4757193 0.6906763
# [6,] 0.4757193 0.4356647
```

**Comment by danielturek** [comment]
The issue here is that the compiled model object (Cpump in your code) has
different values for alpha, beta, and the latent values theta[i], for each
of the two MCMCs you ran. That is, the MCMC chains are starting at
different initial values of the parameters & latent variables, therefor
giving rise to different MCMC chains.

You could fix this, but specifying the exact same initial conditions for
each chain, right before running the MCMC with runMCMC(). You could do this
with Cpump$setInits(initsList), where initsList is a list of initial values.

Keep in touch with other questions, and thanks for your use of NIMBLE.

**Comment by ys-xue** [comment]
Thanks for your quick response! I will try and see if the problem is resolved.

**Comment by ys-xue** [comment]
Worked like a charm! Thank you!
