### ISSUE TITLE
make clear use of nburnin in calculateWAIC relative to nburnin for runMCMC

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble#923]
At moment, I can't tell from the user manual whether the nburnin for calculateWAIC interacts with the nburnin for runMCMC. If one has nburnin>0 for runMCMC, does that mean that calculateWAIC doesn't need to set a burnin?  Based on a quick scan of the code, I think that is the case as calculateWAIC seems to use the mvSamples object, which has already lost the burnin samples.

One more thing is that if nburnin > 0 it looks like use of calculateWAIC might thin the samples _again_, if they have already been thinned by runMCMC.

**Comment by paciorek** [comment]
Ok, I think part of my confusion is that if one uses runMCMC, one presumably just gets WAIC as part of the output and there is no need to call calculateWAIC. Let's make this more clear in the manual and in the help for runMCMC and buildMCMC.

**Comment by danielturek** [comment]
@paciorek Thanks for reading the user manual to this level of detail.

I see that Section 7.4 ("User-friendly execution of MCMC algorithms: runMCMC") doesn't really address this point.  Would a sentence there stating (essentially) "if `WAIC = TRUE` is specified, then the WAIC value is calculated using the post-burnin and post-thinning samples, as specified by the `nburnin` and `thin` arguments."

Same goes for the (earlier) Section 7.1 ("One-line invocation of MCMC: nimbleMCMC"), where the line:
"The above (summary statistics and WAIC) are calculated and returned for each MCMC chain"
could be changed to:
"The above (summary statistics and WAIC) are calculated and returned for each MCMC chain, using post-burnin and post-thinning MCMC samples"

Unrelated, It seems that confusion *could* arise, if a user uses the original, lowest-level way of accessing the MCMC:
- `mcmc$run(nburnin = whatever1)`, and then
- `mcmc$calculateWAIC(nburnin = whatever2)`

Since this would do the burnin twice (first `whatever1`, then subsequently `whatever2`).  Think this is worth addressing in the user manual?

Then, last, Section 7.7 ("Calculating WAIC"), currently says:
"The `calculateWAIC` method has one required argument, `nburnin`, the number of initial samples to discard prior to WAIC calculation.
We could change this to:
"The `calculateWAIC` method has one required argument, `nburnin`, the number of initial samples to discard prior to WAIC calculation, which are discarded subsequent to any discarded samples as specified by the `nburnin` argument to `mcmc$run`."

Thoughts?

**Comment by paciorek** [comment]
Ok, I've done essentially what you suggest.
