### ISSUE TITLE
ddexp does not respect rate parameterization

### ISSUE THREAD

**Issue by perrydv** [nimble-dev/nimble#949]
Reproducible example:
```
library(nimble)

# scalar works fine, both uncompiled and compiled
nf <- nimbleFunction(
  run = function(x = double(), location = double(), scale = double()) {
    ans <- ddexp(x, location, scale = scale)
    return(ans)
    returnType(double())
  }
)

cnf <- compileNimble(nf)
cnf(1.2, 0.5, 0.3)
nf(1.2, 0.5, 0.3)

# rate is over-written by default scale = 1, in both uncompiled and compiled
nf2 <- nimbleFunction(
  run = function(x = double(), location = double(), rate = double()) {
    ans <- ddexp(x, location, rate = rate)
    return(ans)
    returnType(double())
  }
)

cnf2 <- compileNimble(nf2)
cnf2(1.2, 0.5, 0.3) # 0.3 is ignored
nf2(1.2, 0.5, 0.3)  # same value
ddexp(1.2, 0.5, scale = 1) # same value
ddexp(1.2, 0.5, scale = 1/0.3) # correct answer for rate = 0.3
```

The uncompiled problem is related to scale having a default value and also being the native parameterization for the `.Call` to C.  rate is ignored.  (This is different from both dgamma and dinvgamma, which have a default value for the parameter that is not the native one, scale in one case scale and rate in the other.)

A possible solution would be to use 

`.Call(C_ddexp, as.double(x), as.double(location), as.double(1/rate),  as.logical(log))`

If scale was provided, then unfortunately we would be using 1/(1/scale).  An alternative would be to check `if(missing(rate))` and branch on that.

The compiled problem is a little trickier but I have my finger on where to fix it.  I won't go into details here.

@paciorek If you agree I will make a PR with these changes.

**Comment by paciorek** [comment]
Well.... I guess this is partly a result of the fact that it looks like I never set up any tests for use of the rate, probably because scale felt like a more natural parameterization given use of ddexp for lasso/regression type problems. 

But perhaps more likely the reason for this going unnoticed is that (thankfully) it looks like use of ddexp in a nimble model is ok, either with rate used implicitly or explicitly setting 'rate' or explicitly setting 'scale'. 

Sounds like you have your head in it, so feel free to go ahead. I haven't wrapped my head around it.

We should check use of 'var' as well.

**Comment by perrydv** [comment]
I'm not sure we support var for ddexp.

It appears likely that [dpqr]sqrtinvgamma don't compile scale correctly, but I will have to confirm tomorrow.
