### ISSUE TITLE
How to use nimbleFunction to define a y=f(x,theta,gamma) to be used in the nimbleCode?

### ISSUE THREAD

**Issue by zhenglei-gao** [nimble-dev/nimble#97]
In general, I can define a simple function and use it in the nimble codes. An example is given below. However, I couldn't figure out how to define a more complex function. There are two difficulites:
1. I need to pass the newly sampled parameter vector $\theta$ and fixed parameter vector $\gamma$ to the function arguments. I couldn't find an example to do so and I am not sure whether I need the ´setup´ part.
2. My user-defined function will return a vector which is yhat. Because it is derived from solving a differential equation, I cannot make it into a for loop.

I will provide my code for the user defined function in the comment to illustrate the problem.

``` r
library(nimble)

## Define the Deterministic Function

Calc_nimble1 <- nimbleFunction(
  run = function(x = double(1)) {
  returnType(double(1)) #type(nDim, sizes) double(2,c(4,5)) define a matrix
  x <- x+10
  return(x)
})
Calc_nimble1(1:5)
Calc_nimble <- nimbleFunction(
  run = function(x = double(0)) {
  returnType(double(0)) #type(nDim, sizes) double(2,c(4,5)) define a matrix
  x <- x+10
  return(x)
})
Calc_nimble(1:5)
testFUN <- function(x){x+100}
code <- nimbleCode({
  for(i in 1:5){
    mu[i] ~ dnorm(0, 1)
  y[i] <- Calc_nimble(mu[i])
  x ~ dnorm(y[i], 1)
  }


})
# load the NIMBLE library
library(nimble)

## define the model
code <- nimbleCode({
    beta0 ~ dnorm(0, sd = 10000)
    beta1 ~ dnorm(0, sd = 10000)
    sigma_RE ~ dunif(0, 1000)
    for(i in 1:N) {
        beta2[i] ~ dnorm(0, sd = sigma_RE)
        mu[i] <- beta0 + beta1 * x[i] + beta2[i]
        logit(p[i]) <- Calc_nimble(mu[i])
        r[i] ~ dbin(p[i], n[i])
    }
})

## constants, data, and initial values
constants <- list(N = 10)

data <- list(
    r = c(10, 23, 23, 26, 17, 5, 53, 55, 32, 46),
    n = c(39, 62, 81, 51, 39, 6, 74, 72, 51, 79),
    x = c(0,  0,  0,  0,  0,  1, 1,  1,  1,  1)
)

inits <- list(beta0 = 0, beta1 = 0, sigma_RE = 1)

## create the model object
Rmodel <- nimbleModel(code=code, constants=constants, data=data, inits=inits, check = FALSE)

Rmcmc <- buildMCMC(Rmodel)

##Compile the model and MCMC algorithm

Cmodel <- compileNimble(Rmodel)
Cmcmc <- compileNimble(Rmcmc, project = Rmodel)

##Execute MCMC algorithm and extract samples

Cmcmc$run(100)

## NULL

samples <- as.matrix(Cmcmc$mvSamples)
```

**Comment by zhenglei-gao** [comment]
Below are the functions (mainly `SW_Model_calc`) to calculate yhat. 


```{r}
library(ccSolve)
library(plyr)
library(dplyr)
library(reshape)
library(ggplot2)
theme_set(theme_bw())
source_url("https://gist.githubusercontent.com/zhenglei-gao/52dab13c0c67a1b52a70/raw/05dff881651e38be8e7a496aea72cfc77ca2caa5/ModelA_D.r")
n <- 10
yini <- c(100,rep(0,n))
SWModel <- gen.TOXSWA(n=n)
##cat(SWModel)
names(yini) <- c("Pw",paste0("Ps",0:(n-1)))
Zs <- 2
Zsed <- rep(Zs/n,n)
names(Zsed) <- paste0("Zs",0:(n-1))
parms <- c(kpwa = log(2)/50, kpse = log(2)/50, Kd = 50,
           rhob=2.05,theta=0.5,Zw=5,Dp=0.05,delta=1,Zsed)

cToxswaA <- compile.ode(SWModel, language = "C", 
                        parms = parms,y=yini) 
checkTime <- FALSE
if(checkTime) system.time(replicate(1000,{outcA <- ode (func = cToxswaA, y = yini, parms = parms, 
                          times = 0:100)}))
plotSW <- function(dta){
  dta <- data.frame(dta)
  dta <- data.frame(dta[,1:2],Ps=apply(dta[,3:ncol(dta)],1,sum))
  dta <- melt(dta,id.vars=1)
  p <- ggplot(dta,aes(x=time,y=value,color=variable))+geom_line()
  p
}
outcA <- ode (func = cToxswaA, y = yini, parms = parms, 
              times = 0:100)
plotSW(outcA)


```






```{r}
nparms <- length(parms)
yini[1] <- 1
SW_Model_calc(cModel=cToxswaA, optParms=parms[1:3],fixParms=parms[4:nparms],optInis=NULL,fixInis=yini,obsTimes=1:100,
                           transParms = NULL)
```

**Comment by zhenglei-gao** [comment]
Maybe my example is a bit too complicated to be directly answered. I just would like to know whether nimble currently can handle complicated user-defined functions for calculating yhat. In particular,

1. How to pass the to be sampled parameters?
2. How to pass the fixed parameters and time vectors in constant?
3. Do I have to use "for" loops or can I directly use vectorized nodes?

I would appreciate it very much if some of you can have a reproducible example.

**Comment by perrydv** [comment]
Hi Zhenglei,

Thanks for these questions and the previous example.  You are right that I had a hard time knowing exactly what you want to do in a nimbleFunction from your examples.  In the first post I did not see things called “theta” or “gamma” in your code so I am not sure what you were asking.  In the second post I was not sure what part you want to put into a nimbleFunction.  Let me try to answer what I think are some of the relevant issues.  

Here is an example of defining a nimbleFunction that returns a vector for use in a deterministic node of a model.  The model is a one variable linear regression.  (In this case we would not need to provide calculateYhat and could instead write
Yhat[1:N] <- slope + intercept * X[1:N] directly into the model code.  I just separated it into a nimbleFunction for illustration.)

library(nimble)

calculateYhat <- nimbleFunction(
    run = function(slope = double(0), intercept = double(0), X = double(1)) {
        Yhat <- intercept + slope * X
        return(Yhat)
        returnType(double(1))
    })

modelUsingYhat_code <- nimbleCode({
    slope ~ dnorm(0, sd = 100)
    intercept ~ dnorm(0, sd = 100)
    sigma ~ dunif(0, 100)
    Yhat[1:N] <- calculateYhat(slope, intercept, X[1:N])
    for(i in 1:N) Y[i] ~ dnorm(Yhat[i], sd = sigma)
})

X <- rnorm(50)
Y <- rnorm(50)
modelUsingYhat <- nimbleModel(modelUsingYhat_code, constants = list(X = X, N = 50), data = list(Y = Y), inits = list(slope = 0, intercept = 0, sigma = 1))
mcmc <- buildMCMC(modelUsingYhat)

compiled <- compileNimble(modelUsingYhat, mcmc)
compiled$mcmc$run(10000)

I think this answers a couple of your questions.  There is no distinction in a nimbleFunction between parameters to be sampled or other parameters, so I am not sure what you are asking.  Note that in your original example you could also vectorize the logit link.  For example you write (outside the for loop):
p[1:N] <- expit(mu[1:N] + 10)

As illustrated, indices need to be given in the model code but not in a nimbleFunction.

I have been experimenting recently with providing vectorized versions of distributions, so that we can write something like this:
r[1:N] ~ dbin_vec(p[1:N], n[1:N])
This means there is a single vector node r[1:N] rather than N scalar nodes r[i], and dbin_vec is written to calculate the log probability of r[1:N] jointly.  If the other calculations (p[1:N] in this case) are also vectorized, then I’ve seen cases where doing this gives a big improvement in MCMC efficiency.

A compiled nimbleFunction cannot currently call non-nimble compiled code such as your ode solver (if I follow) but that is something we want to write.  It also can’t call an arbitrary R function.

Please follow up with any more specific questions.

Perry

**Comment by zhenglei-gao** [comment]
Hi Perry, 

Thank you very much for your quick answer. Your example answered all my 3 questions. Now I know where is the limit. 

It is great to hear that your are going to have something like an ode solver and also provide nodes with vectorized distributions. Do you have some expected time frame in mind?

About what I would like to do making use of `nimble`, you are right that my `yhat` is calculated by using the ode solver, which in turn actually calls the FORTRAN ODE solver.  For the particular example, I tried to define the transformations and diffusion of a substance in a water-sediment study (OECD 308) in an ODE system and then estimate the parameters by MCMC. Because the parameters are usually highly correlated, a simple optimization won't give "good" answers. But with the help of prior information, which is available in this case, better or more reliable results should be obtained.


FYI, if you are interested, an example of the ODE I tried to solve is defined in the following code:

````
  1: #include <R.h>
  2: 
  3:  
  4:  static double parms[11];
  5: #define kpwa parms[0]
  6: #define kpse parms[1]
  7: #define Kd parms[2]
  8: #define rhob parms[3]
  9: #define theta parms[4]
 10: #define Zw parms[5]
 11: #define Dp parms[6]
 12: #define delta parms[7]
 13: #define Zs0 parms[8]
 14: #define Zs1 parms[9]
 15: #define Zs2 parms[10]
 16: 
 17: void initpar(void (* odeparms)(int *, double *)){
 18:     int N =11;
 19:     odeparms(&N, parms);
 20: }
 21: 
 22: void func ( int * n, double * t, double * y, double * f, double * rpar, int * ipar ) {
 23: 
 24:   
 25:   
 26:  double  Pw, Ps0, Ps1, Ps2 ;
 27:  
 28:  double  dPw, dPs0, dPs1, dPs2 ;
 29:  
 30:  
 31:   
 32:  Pw = y[0];
 33:  Ps0 = y[1];
 34:  Ps1 = y[2];
 35:  Ps2 = y[3];
 36:   
 37:   double fdiss= 1/(1+Kd*rhob/theta);
 38:   dPw = -kpwa*Pw-2*Dp/(Zs0)*(Pw/Zw-fdiss*Ps0/Zs0);
 39:   dPs0 = -kpse*Ps0+2*Dp/(Zs0)*(Pw/Zw-fdiss*Ps0/Zs0)-2*Dp*fdiss/(Zs0+Zs1)*(Ps0/Zs0-Ps1/Zs1);
 40: dPs1= -delta*kpse*Ps1+2*Dp*fdiss/(Zs0+Zs1)*(Ps0/Zs0-Ps1/Zs1)-2*Dp*fdiss/(Zs1+Zs2)*(Ps1/Zs1-Ps2/Zs2);
 41: dPs2= -delta*kpse*Ps2+2*Dp*fdiss/(Zs1+Zs2)*(Ps1/Zs1-Ps2/Zs2);
 42:  
 43:  f[0] = dPw;
 44:  f[1] = dPs0;
 45:  f[2] = dPs1;
 46:  f[3] = dPs2;
 47:   
 48: 
 49: }
````

**Comment by perrydv** [comment]
Thanks Zhenglei.

I know of other users who would be interested in being able to call user-provided compiled code.  I think it is a problem where a quick solution could be quite feasible but a more elegant solution could take some time.  I can’t say right now when we’ll get to it, but I’ll give it some thought and try to prioritize it.

I’m going to leave this issue open to serve as a reminder for us.

Perry

**Comment by zhenglei-gao** [comment]
Hi Perry, 

Just some related information. Following the advice of rcppbugs's author,  I tried the same model in STAN but the sampling freezes possibly due to the stiffness of the ODEs. The code and models for STAN were included in  [here](https://groups.google.com/forum/#!topic/stan-users/dIx5E_yrp6c) in the stan user mailing list.

**Comment by perrydv** [comment]
This issue was left open inadvertently.  The need to be able to call external code was provided in `nimbleExternalCall` and `nimbleRcall`.  I am closing the issue now.
